src/IO.Ably.Tests/Realtime/ChannelSandboxSpecs.cs

when running the test suite AttachAwaitShouldtimeoutIfStateChanges would frequently fail (approximately 8/10 runs it would fail on my machine)
This appears to be caused by the call to `await channel.AttachAsync();` completing before the event from the call to Close the transport had bubbled up. In that case there is no error in the result and the `result.Error.Should().NotBeNull();` assertion fails.
Moving the bulk of the assertions into the Connected handler solves this.
I have added a new assertion to prove the Connection handler was fired to avoid a possible false positive.

test AttachAwaitShouldtimeoutIfStateChanges would frequently fail

---

src/IO.Ably.Shared/AuthOptions.cs

Improve XML Doc for AuthCallBack, see https://github.com/ably/ably-dotnet/issues/141 for details

Improve the XML Docs for AuthCallback

---

.gitignore
GitVersion.yml
README.md
default.ps1
nuget/io.ably_msgpack.nuspec
package.ps1

Add release process to readme per request in issue #149 
@marto83 could you please review and amend as necessary please?

Add Release Process

---

src/IO.Ably.Shared/Realtime/RealtimeChannels.cs
src/IO.Ably.Tests/Realtime/ChannelsSpecs.cs

This is a fix for issue #167 which was caused by an error on my part that meant ChannelOptions could be reset.
I have fixed the offending code and have added a new test to prevent this happening again.

fix for issue 167

---

.circleci/config.yml
src/IO.Ably.Tests.Shared/Realtime/ChannelSandboxSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionFallbackSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/CountDownTimerSpecs.cs

I have made some tweaks to tests, mainly allowing some intermittent test to retry and I have added a Circle CI config that will run the tests with dotnet core 2 on linux

Test and ci improvements

---

src/IO.Ably.Shared/Transport/MsWebSocketConnection.cs
src/IO.Ably.Shared/Transport/MsWebSocketTransport.cs
src/IO.Ably.Tests.Shared/Infrastructure/TestTransportWrapper.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs

Fix for the null reference errors mentioned in #171

Null check WebSocket Client

---

README.md

- Moved the Supported Platforms section closer to the top of the README
- Added version information for Xamarin iOS and Android and mono.
- Added a note about Unity support.

updated Supported Platforms section in README

---

src/IO.Ably.Shared/Realtime/Presence.cs

This fixes the delay caused due to WaitForSyncAsync not picking up sync complete the first time, described in issue https://github.com/ably/ably-dotnet/issues/204

Fix delay in initial presence sync

---

src/IO.Ably.Shared/AuthOptions.cs
src/IO.Ably.Tests.Shared/AuthTests/AuthOptionsTests.cs

A small addition to the existing tests for RSA8e to validate the property names and access level of the AuthOptions

RSA8e test improvement 

---

src/IO.Ably.Shared/AblyAuth.cs
src/IO.Ably.Tests.Shared/AuthTests/AuthorizeTests.cs

`(RSA10k) If the AuthOption argument’s queryTime attribute is true, it will obtain the server time once and persist the offset from the local clock. All future token requests generated directly or indirectly via a call to authorize will not obtain the server time, but instead use the local clock offset to calculate the server time.`
Internally the library uses `DateTimeOffset.UtcNow` I have not done any work related to the following part of the RSA10k spec as it didn't seem relevant.
`The client library itself MAY internally discard the cached local clock offset in situations in which it may have been invalidated, such as if there is a local change to the date, time, or timezone, of the client device. For clarity however, there is no requirement for this cache invalidation to be available …

changes and tests to support RSA10k

---

src/IO.Ably.Shared/ClientOptions.cs
src/IO.Ably.Shared/Http/AblyHttpClient.cs
src/IO.Ably.Shared/Http/AblyHttpOptions.cs
src/IO.Ably.Shared/Realtime/Connection.cs
src/IO.Ably.Shared/Transport/TransportParams.cs
src/IO.Ably.Tests.Shared/Rest/RestSpecs.cs

Basic support for `(TO3k6) fallbackHosts`

Hotfix for issue 216

---

src/IO.Ably.Shared/AblyAuth.cs
src/IO.Ably.Shared/ApiKey.cs
src/IO.Ably.Shared/TokenDetails.cs
src/IO.Ably.Shared/Transport/ConnectionManager.cs
src/IO.Ably.Shared/Transport/States/Connection/ConnectionConnectedState.cs
src/IO.Ably.Shared/Transport/States/Connection/ConnectionConnectingState.cs
src/IO.Ably.Shared/Transport/TransportParams.cs
src/IO.Ably.Tests.Shared/Infrastructure/TaskCompletionAwaiter.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionFailureSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionFailuresOnceConnectedSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/EventEmitterSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionStateTests/ConnectingStateSpecs.cs

Updates to support the changes in the v1.0 spec to RTN14a, RTN14b and the addition of RTN15h.

RTN14a, RTN14b, RTN15h

---

README.md

Add an explicit mention of .NET Core support.
Change to use MS capitalisation of .NET.
Replaced asterisk with &ast; and &dagger; to allow better formatting in Markdown.

Update README.md to cover .NET Core support

---

src/IO.Ably.Tests.Shared/Realtime/ChannelSpecs.cs

Expanded tests to cover RTL2d
- (RTL2d) A ChannelStateChange object is emitted as the first argument for every ChannelEvent (including both RTL2a state changes and RTL2g UPDATE events). It may optionally contain a reason consisting of an ErrorInfo object; any state change triggered by a ProtocolMessage that contains an error member should populate the reason with that error in the corresponding state change event

RTL2d tests

---

README.md

I have also created an end-to-end example of using AuthCallback [here](https://github.com/withakay/ably-dotnet-authcallbackexample) if that is of interest.

update README with better AuthCallback example

---

README.md

added notes to the README on one method to reference a project from source.

Notes on how to reference a project from source.

---

src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs

A test to cover RTP2e
- (RTP2e) If a SYNC is not in progress, then when a presence message with an action of LEAVE arrives, that memberKey should be deleted from the presence map, if present.

Test for RTP2e

---

src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs

- (RTP16a) If the connection is CONNECTED and the channel is ATTACHED then all presence messages are published immediately

test for RTP16a

---

src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs

- (RTP5c3) If any of the automatic ENTER presence messages published in RTP5c2 fail, then an UPDATE event should be emitted on the channel with resumed set to true and reason set to an ErrorInfo object with error code value 91004 and the error message string containing the message received from Ably (if applicable), the code received from Ably (if applicable) and the explicit or implicit client_id of the PresenceMessage

Test cover for RTP5c3

---

README.md

Ahead of 1.1 release, we need feature support info in all READMEs

Known limitations section in README

---

src/IO.Ably.Shared/AblyAuth.cs
src/IO.Ably.Shared/Http/AblyHttpClient.cs
src/IO.Ably.Shared/Http/AblyResponse.cs
src/IO.Ably.Shared/HttpUtility.cs
src/IO.Ably.Shared/Types/ErrorInfo.cs
src/IO.Ably.Tests.Shared/ErrorInfoTests.cs
src/IO.Ably.Tests.Shared/IO.Ably.Tests.Shared.projitems
src/IO.Ably.Tests.Shared/Rest/JwtSandboxSpec.cs

Minor changes to support JWT and tests.

JWT support

---

src/IO.Ably.Tests.DotNetCore20/IO.Ably.Tests.DotNetCore20.csproj
src/IO.Ably.Tests.NETFramework/IO.Ably.Tests.NETFramework.csproj

House keeping: updating some packages used by the test projects

update xunit and moq to latest versions

---

src/IO.Ably.Shared/Transport/MsWebSocketConnection.cs

Prevent accessing `ClientWebSocket` when `MsWebSocketConnection` has been disposed, this avoids a potential `ObjectDisposedException`

Dispose guarding

---

README.md
azure-pipelines-core.yml
azure-pipelines.yml
nuget/io.ably.nuspec
nuget/io.ably_msgpack.nuspec
src/IO.Ably.Shared/Result.cs
src/IO.Ably.Shared/TaskConstants.cs
src/IO.Ably.Shared/Types/ErrorInfo.cs

Per [the plan](https://docs.google.com/document/d/1fhbQWQaoIe-urizplgNtT4WxPRgoUDchg-VIBnAEqA0/edit?usp=sharing) (internal link).

Rename master to main

---

src/IO.Ably.Shared/AblyAuth.cs
src/IO.Ably.Shared/Realtime/Workflows/RealtimeCommands.cs
src/IO.Ably.Shared/Realtime/Workflows/RealtimeWorkflow.cs
src/IO.Ably.Shared/TokenDetails.cs
src/IO.Ably.Tests.Shared/AuthTests/AuthSandboxSpecs.cs
src/IO.Ably.Tests.Shared/AuthTests/AuthorizeTests.cs
src/IO.Ably.Tests.Shared/AuthTests/TestAblyAuth.cs
src/IO.Ably.Tests.Shared/Infrastructure/FakeAuth.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionSandboxTransportSideEffectsSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionFailuresOnceConnectedSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ExtraSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/RealtimeSandboxSpecs.cs
src/IO.Ably.Tests.Shared/Rest/ChannelSandboxSpecs.cs
src/IO.Ably.Tests.Shared/Rest/RestSpecs.cs

- Removed token expiry check from auth flow
- Fixes #303

Fix auth token clock-skew

---

src/IO.Ably.Tests.Shared/Infrastructure/AblySpecs.cs
src/IO.Ably.Tests.Shared/Rest/ChannelSandboxSpecs.cs

- Added few more tests
- Fixes #237

Idempotent Rest Publish

---

README.md

- Added console app documentation
- Fixes #455

Console app documentation

---

src/IO.Ably.Shared/AblyAuth.cs
src/IO.Ably.Tests.Shared/AuthTests/TestAblyAuth.cs
src/IO.Ably.Tests.Shared/Infrastructure/AblySpecs.cs

- Refactored ServerNow implementation
- References #441

Fix client time drift

---

CHANGELOG.md
src/CommonAssemblyInfo.cs

- fix/499 add connectionKey prop [\#499](https://github.com/ably/ably-dotnet/pull/499) ([jasonmsmith](https://github.com/jasonmsmith))

Update Changelog and bump version to 1.2.4

---

src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionSandboxTransportSideEffectsSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/DeltaSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/RealtimeSandboxSpecs.cs
src/IO.Ably.Tests.Shared/Rest/ChannelSandboxSpecs.cs
src/IO.Ably.Tests.Shared/Rest/PresenceSandboxSpecs.cs

Once we've got a stable green CI I plan to create GitHub issues for each of these so we can track the debt.

Disable failing tests

---

README.md

Some minor spelling and consistency fixes for the `readme.md`.

Update readme for spelling and consistency

---

src/IO.Ably.Shared/AblyRest.cs
src/IO.Ably.Shared/ClientOptions.cs
src/IO.Ably.Shared/Http/AblyHttpClient.cs
src/IO.Ably.Shared/Http/AblyHttpOptions.cs
src/IO.Ably.Tests.Shared/Rest/AblyHttpClientSpecs.cs
src/IO.Ably.Tests.Shared/Rest/RestSpecs.cs

Experiment to see if CI is a bit more robust.
This is an update of the work done by Sachin in the PR https://github.com/ably/ably-dotnet/pull/489 .
If this PR is approved I will close Sachin's.

Add AddRequestId property to ClientOptions

---

src/IO.Ably.Shared/Realtime/Workflows/RealtimeCommands.cs
src/IO.Ably.Shared/Types/ProtocolMessage.cs

Fix some typos in string literals.

---

src/IO.Ably.Shared/AblyRest.cs
src/IO.Ably.Shared/CipherParams.cs
src/IO.Ably.Shared/Encryption/AesCipher.cs
src/IO.Ably.Shared/Encryption/Crypto.cs
src/IO.Ably.Shared/EventEmitter.cs
src/IO.Ably.Shared/Extensions/EnumerableExtensions.cs
src/IO.Ably.Shared/Extensions/TaskExtensions.cs
src/IO.Ably.Shared/HttpPaginatedResponse.cs
src/IO.Ably.Shared/HttpUtility.cs
src/IO.Ably.Shared/IAuthCommands.cs
src/IO.Ably.Shared/Realtime/ChannelEvent.cs
src/IO.Ably.Shared/Realtime/ChannelProperties.cs
src/IO.Ably.Shared/Realtime/ConnectionEvent.cs
src/IO.Ably.Shared/Realtime/ConnectionState.cs
src/IO.Ably.Shared/Realtime/Presence.cs
src/IO.Ably.Shared/Rest/IRestChannel.cs
src/IO.Ably.Shared/Result.cs
src/IO.Ably.Shared/Statistics.cs
src/IO.Ably.Shared/TokenDetails.cs
src/IO.Ably.Shared/Types/ProtocolMessage.cs

Fix various spelling issues in API Doc Comments.

Fix API Doc Comment Spelling

---

src/IO.Ably.Shared/IO.Ably.Shared.projitems
src/IO.Ably.Shared/Push/ActivationStateMachine.Events.cs
src/IO.Ably.Shared/Push/ActivationStateMachine.cs

Add all the Events for the ActivationStateMachine.

Add State machine and available events.

---

src/IO.Ably.Shared/DefaultLogger.cs

Fix internal method name spelling.

Fix internal method name spelling.

---

src/IO.Ably.Shared/IRealtimeClient.cs
src/IO.Ably.Shared/IRestClient.cs
src/IO.Ably.Shared/Push/ActivationStateMachine.cs
src/IO.Ably.Tests.Shared/ClientOptionsTests.cs

Remove redundant `using` statements.

Remove redundant 'using' statements

---

src/IO.Ably.NETStandard20/Properties/AssemblyInfo.cs
src/IO.Ably.Push.Android/AndroidMobileDevice.cs
src/IO.Ably.Push.Android/IO.Ably.Push.Android.csproj
src/IO.Ably.Push.Android/Resources/Resource.Designer.cs
src/IO.Ably.Push.Android/packages.config
src/IO.Ably.Shared/Push/ActivationStateMachine.States.cs
src/IO.Ably.Shared/Push/ActivationStateMachine.cs
src/IO.Ably.Shared/Push/IMobileDevice.cs

I've put a task for myself to make `io.ably.broadcast.` a const

Implement intent logic

---

src/IO.Ably.Shared/Realtime/Workflows/RealtimeState.cs

Make `WaitingForAck` field `readonly`.

Make 'WaitingForAck' field 'readonly'

---

src/IO.Ably.Shared/ClientOptions.cs
src/IO.Ably.Shared/Realtime/Workflows/RealtimeCommands.cs
src/IO.Ably.Shared/Realtime/Workflows/RealtimeState.cs
src/IO.Ably.Shared/Realtime/Workflows/RealtimeWorkflow.cs
src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs

https://github.com/ably/ably-dotnet/pull/511 .

Add heartbeat monitor

---

src/IO.Ably.Shared/MessageEncoders/CipherEncoder.cs
src/IO.Ably.Shared/MessageEncoders/JsonEncoder.cs
src/IO.Ably.Shared/MessageEncoders/VCDiffEncoder.cs

The compiler will generate these for us.

Remove redundant empty ctor

---

src/IO.Ably.Tests.Shared/JsonMessageSerializerTests.cs
src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ProtocolMessageSpecs.cs
src/IO.Ably.Tests.Shared/Rest/RestSpecs.cs

Remove redundant explicit type in array creation.

Remove redundant type in array creation

---

src/IO.Ably.Shared/Push/ActivationStateMachine.States.cs
src/IO.Ably.Shared/Realtime/Workflows/RealtimeWorkflow.cs
src/IO.Ably.Tests.Shared/AuthTests/AuthorizationTests.cs
src/IO.Ably.Tests.Shared/CustomSerializers/MessageExtrasConverterTests.cs
src/IO.Ably.Tests.Shared/DataRequestQueryParseTests.cs
src/IO.Ably.Tests.Shared/IO.Ably.Tests.Shared.projitems
src/IO.Ably.Tests.Shared/MessageEncodes/MessageEncodersAcceptanceTests.cs
src/IO.Ably.Tests.Shared/MessageEncodes/Utf8EncoderTests.cs
src/IO.Ably.Tests.Shared/Realtime/ChannelSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionAttemptsInfoSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionFailureSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionFailuresOnceConnectedSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionStateTests/ClosedStateSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionStateTests/ClosingStateSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionStateTests/ConnectedStateSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionStateTests/ConnectingStateSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionStateTests/DisconnectedStateSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionStateTests/FailedStateSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionStateTests/InitializedStateSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionStateTests/SuspendedStateSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/RealtimeSpecs.cs
src/IO.Ably.Tests.Shared/Rest/ChannelSandboxSpecs.cs
src/IO.Ably.Tests.Shared/Rest/ChannelSpecs.cs
src/IO.Ably.Tests.Shared/Rest/PresenceSpecs.cs
src/IO.Ably.Tests.Shared/Rest/RequestSandBoxSpecs.cs
src/IO.Ably.Tests.Shared/Rest/RestSpecs.cs
src/IO.Ably.Tests.Shared/StatsParsingTests.cs
src/IO.Ably.Tests.Shared/TokenRequestPopulateTests.cs

Fixing missing `readonly`ness and associated secondary issues.

Fix missing 'readonly'-ness

---

src/IO.Ably.NetFramework.sln
src/IO.Ably.NetStandard.sln
src/IO.Ably.Package.sln
src/IO.Ably.UWP.sln
src/IO.Ably.Xamarin.sln
src/IO.Ably.sln

This just removes the project references to the `nuspec' file deleted in PR https://github.com/ably/ably-dotnet/pull/585 .

Remove project references to deleted 'nuspec' file.

---

src/IO.Ably.NetFramework.sln
src/IO.Ably.NetStandard.sln
src/IO.Ably.Package.sln
src/IO.Ably.UWP.sln
src/IO.Ably.Xamarin.sln
src/IO.Ably.sln

Remove project reference to non-existing `appveyor.yml`.

Remove project ref to 'appveyor.yml'

---

src/IO.Ably.Tests.NETFramework/IO.Ably.Tests.NETFramework.csproj

Remove the unused `Castle Core` test dependency.

Remove unused 'Castle Core' depedency

---

README.md

Update the `readme.md` focusing on code samples and platform support.

Update 'readme.md' sample code and platforms

---

src/IO.Ably.Tests.Shared/Samples/DocumentationSamples.cs
src/IO.Ably.Tests.Shared/Samples/RealtimeSamples.cs

Update the documentation samples to bring them into line with the
recently updated `readme.md`.

Update documentation samples

---

src/IO.Ably.Shared/CapabilityResource.cs

Gentle tidy up for Base Class Library / Framework Design Guidelines conformance.  Also removed unnecessary state mutators.

Refactor 'CapabilityResource'

---

src/IO.Ably.Shared/Realtime/PresenceMap.cs

Removed unnecessary virtuals, properties and layout type along .NET BCL FDG lines.

Refactor 'PresenceMap'

---

src/IO.Ably.Shared/Http/AblyHttpClient.cs

Refactor the `AblyHttpClient` ahead of adding in the `Ably-Agent` header support.

Refactor 'AblyHttpClient'

---

src/IO.Ably.Shared/Http/AblyResponse.cs

Tighten up encapsulation, re-org and remove unused property.

Tidy the 'AblyResponse'

---

src/IO.Ably.Shared/IO.Ably.Shared.projitems
src/IO.Ably.Shared/Rest/RestChannel.cs

Also fix layout to follow BCL / FDG.

Rename 'RestChannel' file to match type name

---

src/IO.Ably.Tests.Shared/IO.Ably.Tests.Shared.projitems
src/IO.Ably.Tests.Shared/Rest/SandboxSpecs.cs

Also reordered type members to follow BCL FDG and removed unused method.

Rename 'SandboxSpecs' file to match type name

---

src/IO.Ably.Shared/Push/PushAdmin.cs

Remove unused `using`'s and fix type layout for BCL FDG.

Tidy 'PushAdmin' type

---

src/IO.Ably.Shared/Push/ActivationStateMachine.cs
src/IO.Ably.Shared/Push/PersistKeys.cs
src/IO.Ably.Tests.Shared/Push/ActivationStateMachineTests.cs

.NET types do not using screaming caps

---

src/IO.Ably.Shared/Types/ErrorInfo.cs

Replace magic number `80002` with `ErrorCodes.ConnectionSuspended` enum.

Replace magic number with 'ConnectionSuspended' enum

---

src/IO.Ably.Tests.Shared/Infrastructure/ResourceHelper.cs

Using this form reduces the level of nesting.

Prefer the 'using' declaration form

---

src/IO.Ably.Shared/Push/ListDeviceDetailsRequest.cs
src/IO.Ably.Tests.Shared/IO.Ably.Tests.Shared.projitems
src/IO.Ably.Tests.Shared/Push/ListDeviceDetailsRequestTests.cs

Add tests for the `ListDeviceDetailsRequest` and tidy up the type a little.

'ListDeviceDetailsRequest' add tests

---

src/IO.Ably.Shared/AblyAuth.cs

Pass AuthCallback exception to ErrorInfo to make it easier for debugging

---

src/IO.Ably.Shared/Push/ActivationStateMachine.Events.cs

Remove unused 'GettingPushDeviceDetailsFailed' class

---

src/IO.Ably.Tests.Shared/Infrastructure/ConditionalAwaiter.cs

Fixes layout, missing `readonly` and unnecessary initialization.

'ConditionalAwaiter' fix various static code analysis warnings

---

src/IO.Ably.Shared/Transport/ConnectionAttemptsInfo.cs

Also replace `internal` property with `private` state since nothing outside of the actual implementation uses it.

'ConnectionAttemptsInfo' make methods private

---

src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs

Fix connection key update test

---

.gitignore

Removing the ATL and Visual C++ patterns.

Tidy up '.gitignore'

---

src/IO.Ably.Tests.Shared/Push/PushAdminTests.cs

'PushAdminTests' replace lambdas with local functions

---

src/IO.Ably.Tests.Shared/Push/LocalDeviceTests.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionFailuresOnceConnectedSpecs.cs

I will create Issues for each of these to track their progress.

Skip intermittently failing tests

---

src/IO.Ably.Tests.Shared/Realtime/CountDownTimerSpecs.cs

This PR reduces a bunch of diplicated code in the `CountdownTimer` tests and also removes some associated warnings.

'CountdownTimer' specs, reduce duplicated code

---

src/IO.Ably.Tests.Shared/Realtime/ChannelSpecs.cs

Also, tweak modifiers declaration order.

Fix possible 'NullReferenceException'

---

src/IO.Ably.Shared/Realtime/Presence.cs
src/IO.Ably.Tests.Shared/Infrastructure/FakeTransport.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionPingSpecs.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/EventEmitterSpecs.cs
src/IO.Ably.Tests.Shared/Rest/SandboxSpecs.cs

Fixes use of async lambdas with delegates that return void.

Fix use of async lambda with a delegate that returns void

---

src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs

Fixed RTP19

---

src/IO.Ably.Tests.Shared/Rest/PresenceSandboxSpecs.cs

Fix channel presence skipped test

---

CHANGELOG.md
src/CommonAssemblyInfo.cs

Release 1.2.6

---

src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs

Presence test - Internal Map ConnectionId

---

src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs

Emit member leaves on no has_presence

---

src/IO.Ably.Shared/Realtime/PresenceMap.cs
src/IO.Ably.Tests.Shared/Infrastructure/TestTransportWrapper.cs
src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
src/IO.Ably.Tests.Shared/TestExtensions.cs

Presence map behavior

---

src/IO.Ably.Shared/Realtime/Presence.cs
src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs

Channel presence sync with no members

---

src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs

Fix Channel Presence Sync Internal Map

---

src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs

Fix internal map test

---

src/IO.Ably.Tests.Shared/Rest/ChannelSandboxSpecs.cs

Fix idempotent publish simulate retry test

---

src/IO.Ably.Tests.Shared/Realtime/ConnectionSandboxOperatingSystemEventsForNetworkSpecs.cs

Fix operating system network state change test

---

src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs

Fix channel attack send queued messages

---

src/IO.Ably.Tests.Shared/Realtime/ConnectionSandboxOperatingSystemEventsForNetworkSpecs.cs

Fix Detect operating system network change

---

src/IO.Ably.Shared/AblyAuth.cs
src/IO.Ably.Tests.Shared/Rest/RestInitSpecs.cs

- Fixed auth logging level from error to warning

Fixed auth warning log message

---

src/IO.Ably.Tests.Shared/Realtime/ConnectionSandboxTransportSideEffectsSpecs.cs

Resend detach on reconnect

---

README.md
src/IO.Ably.Shared/IO.Ably.Shared.projitems
src/IO.Ably.Shared/Rest/ChannelDetails.cs
src/IO.Ably.Shared/Rest/IRestChannel.cs
src/IO.Ably.Shared/Rest/RestChannel.cs
src/IO.Ably.Tests.Shared/Rest/ChannelSandboxSpecs.cs

Add channel lifecycle support

---

src/IO.Ably.Shared/Realtime/Connection.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionRecoverySpecs.cs

https://github.com/ably/specification/pull/88#discussion_r1002458855

Rename getRecoveryKey->createRecoveryKey per updated spec

---

src/IO.Ably.Shared/Defaults.cs
src/IO.Ably.Shared/Realtime/Connection.cs

- Updated protocol version to integer here -> https://github.com/ably/ably-dotnet/pull/1198/commits/91d0385743dddc90f40cb4cdc3eb7137f431ab09
- AblyRest#Request doesn't take version as a param, so no change needed there.
- Fixed #1187

Update integration 2.0 spec

---

src/IO.Ably.Shared/AblyAuth.cs
src/IO.Ably.Shared/IAblyAuth.cs
src/IO.Ably.Tests.Shared/AuthTests/AuthSandboxSpecs.cs
src/IO.Ably.Tests.Shared/AuthTests/AuthorizationTests.cs
src/IO.Ably.Tests.Shared/AuthTests/RequestTokenSpecs.cs
src/IO.Ably.Tests.Shared/Infrastructure/TaskCompleterAwaiterTests.cs
src/IO.Ably.Tests.Shared/Rest/RestSpecs.cs
src/IO.Ably.Tests.Shared/Samples/DocumentationSamples.cs
src/IO.Ably.Tests.Shared/Samples/RealtimeSamples.cs

Fix authCallback token string

---

README.md
src/IO.Ably.Shared/AblyRealtime.cs
src/IO.Ably.Shared/ClientOptions.cs

Support customContext 

---

README.md

- Supposed to be added as a part of #1139 
- Example given here https://github.com/ably/ably-dotnet/issues/1182#issuecomment-1237644878

Add logging doc

---

.github/workflows/package.yml

Fix unity packager github workflow

---

src/IO.Ably.Android/Properties/AssemblyInfo.cs
src/IO.Ably.NETFramework/Properties/AssemblyInfo.cs
src/IO.Ably.NETStandard20/Properties/AssemblyInfo.cs
src/IO.Ably.Shared/Defaults.cs
src/IO.Ably.Shared/Realtime/ConnectionStateChangedEventArgs.cs
src/IO.Ably.Tests.Shared/Samples/RealtimeSamples.cs
src/IO.Ably.iOS/Properties/AssemblyInfo.cs

Fix ably io urls

---

README.md
src/IO.Ably.Android/Properties/AssemblyInfo.cs
src/IO.Ably.NETFramework/Properties/AssemblyInfo.cs
src/IO.Ably.NETStandard20/Properties/AssemblyInfo.cs
src/IO.Ably.Shared/Defaults.cs
src/IO.Ably.Shared/Realtime/ConnectionStateChangedEventArgs.cs
src/IO.Ably.Tests.Shared/Rest/RequestSandBoxSpecs.cs
src/IO.Ably.Tests.Shared/Samples/RealtimeSamples.cs
src/IO.Ably.iOS/Properties/AssemblyInfo.cs

Update doc+tests for batch publish

---

src/IO.Ably.Shared/Defaults.cs
src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs

Updated connectionTtl to be 120 seconds

---

README.md

-  update csproj for maui issue related to ios signed release
- Updated readme as per fix #1259

updated readme for maui config

---

.ably/capabilities.yaml
README.md
unity/README.md

Fix readme and capabilities

---

.github/workflows/package.yml
.github/workflows/run-tests-linux.yml
.github/workflows/run-tests-macos.yml
.github/workflows/run-tests-windows.yml
README.md
global.json
src/IO.Ably.Shared/AblyAuth.cs
src/IO.Ably.Shared/IAblyAuth.cs
src/IO.Ably.Tests.Shared/AuthTests/AuthSandboxSpecs.cs
src/IO.Ably.Tests.Shared/AuthTests/AuthorizationTests.cs
src/IO.Ably.Tests.Shared/AuthTests/RequestTokenSpecs.cs
src/IO.Ably.Tests.Shared/Infrastructure/ConditionalAwaiter.cs
src/IO.Ably.Tests.Shared/Infrastructure/TaskCompleterAwaiterTests.cs
src/IO.Ably.Tests.Shared/Realtime/ChannelSpecs.cs
src/IO.Ably.Tests.Shared/Rest/RequestSandBoxSpecs.cs
src/IO.Ably.Tests.Shared/Rest/RestSpecs.cs
src/IO.Ably.Tests.Shared/Samples/DocumentationSamples.cs
src/IO.Ably.Tests.Shared/Samples/RealtimeSamples.cs
src/IO.Ably.Tests.Shared/StatsParsingTests.cs

Fix Create token request
