- src/Ably.AcceptanceTests/RealtimeChannelAcceptanceTests.cs
- src/Ably.Core/AblyBase.cs
- src/Ably.Core/AblyRealtimeOptions.cs
- src/Ably.Core/AuthOptions.cs
- src/Ably.Core/IPaginatedResource.cs
- src/Ably.Core/MessageEncoders/MessageHandler.cs
- src/Ably.Core/Realtime/Channel.cs
- src/Ably.Core/Realtime/ChannelState.cs
- src/Ably.Core/Realtime/ConnectionState.cs
- src/Ably.Core/Realtime/Presence.cs
- src/Ably.Core/RestClient.cs
- src/Ably.Tests/CapabilityTests.cs
- src/Ably.Tests/Realtime/PresenceTests.cs
- src/Ably.Tests/Realtime/RealtimeChannelTests.cs
- src/Ably.Tests/RestTests.cs
See discussion in https://github.com/ably/wiki/issues/68
blind whole-repo `s/nitialis/nitializ/`' - haven't tested it, so please test before merging
> Standardise on 'initialized' for channel/connection state etc

- src/IO.Ably.Shared/Logger.cs
- src/IO.Ably.Tests/LoggerTests.cs
I have pushed down the static Logger code into an internal class (InternalLogger) that can be instanced from the test suite. This prevents interactions when running tests in parallel. The Logger interface (small 'i') is unchanged and uses a singleton instance of InternalLogger to do its work.
> Isolated logger for reliable testing

- src/IO.Ably.Tests/App.config
Assembly binding redirects were causing the test runner to look for an out of date assembly, which caused it to throw an error and thus not run any tests.
Removing the redirects solves the issue
> Removed obsolete assembly binding redirects from the Test project

- src/IO.Ably.Tests/Rest/RestSpecs.cs
This fixes a couple of tests that occasionally fail because they have interactions, caused by the static logger
> update the rest spec tests to use the InternalLogger

- src/IO.Ably.Shared/Realtime/Channel.cs
Using the existing IsTerminalConnectionState (which returns true if the connection is Closed, Closing, Suspended Or Failed and false otherwise) to check if an exception should be thrown when attaching a channel as per RTL4b.
This feature is covered by [this test](https://github.com/ably/ably-dotnet/blob/025cf1e2eccfd3e544e64d0f0da98ca75ac7e343/src/IO.Ably.Tests/Realtime/ChannelSpecs.cs#L268), which now passes.
> A fix to comply with RTL4b 

- src/IO.Ably.Tests/Realtime/ChannelSandboxSpecs.cs
- src/IO.Ably.Tests/Realtime/ChannelSpecs.cs
- src/IO.Ably.Tests/Realtime/ConnectionSandBoxSpecs.cs
- src/IO.Ably.Tests/Realtime/CountDownTimerSpecs.cs
I have updated some tests I found to be unreliable because they were assuming a valid response would arrive with in a certain time frame, which was true when the tests were run in isolation, but often not so when the whole suite was run.
Most of the fixes involve changing code like this
`await Task.Delay(100);`
to something like this
`for (var i = 0; i < 10; i++)
{
if (expectedResult)
break;
else        
await Task.Delay(100);
}`
Which I hope is fairly self explanatory.
For one test it made more sense to use a TaskCompletionSource.
> Updates to some test that rely on a delays

- src/IO.Ably.Shared/Transport/ConnectionManager.cs
Previously messages would be added to a list if the Connection Manager was transitioning to a new state, but processed immediately if not. 
If found this logic quite hard to follow when looking for possible race conditions but I could see the intent, so I have changed it so all messages are queued using a ConcurrentQueue and if the state is not transitioning when the message is received, the queue is processed. 
Additionally I have changed the way OnTransportDataReceived is executed, previously this was wrapped in Task that had task.ConfigureAwait(false) called on it, this has the effect of running the task on a new thread (from the thread pool) and returning immediately (essentially fire and forget), which has the potential to jumble the message ordering. 
I could not see any benefit to …
> simplified the message queue logic in ConnectionManager

- src/IO.Ably.Tests/Realtime/ConnectionSandBoxSpecs.cs
- src/IO.Ably.Tests/Realtime/PresenceSandboxSpecs.cs
- src/IO.Ably.Tests/Rest/RestSpecs.cs
I have improved a test that was testing for something to be random, previously there was 1/36 chance the test would fail (6 hosts), I now run the connection logic 20 times and compare that for a 1/14400 chance of a false negative.
Additionally I have marked some tests that always fail to be skipped (and labelled as TODO) for now.
> Test improvements & skip some tests.

- .gitignore
- GitVersion.yml
- README.md
- default.ps1
- nuget/io.ably_msgpack.nuspec
- package.ps1
I have updated the way that versioning is managed.
There is now a GitVersion.yml file that works with GitVersion.exe.
The nuspec files now use a $version$ variable that is passed in from the build script, the build script picks up the versions from GitVersion. 
Now, when creating a package from the master branch the version string will be the plain SerVer 'Maj.Min.Patch' as normal, but on feature branches the version string will contain the branch name and subversion e.g. '0.8.5-feature-branch-a0001', this would become a nuget package called 'ably.io.0.8.5-feature-branch-a0001.nupkg'. 
The reason this is useful is because I wanted to be able to test prerelease builds without polluting the main nuget repository, so I have set up a seperate package repository just for this on myget.org …
> Update release process

- default.ps1
- functions.ps1
- src/IO.Ably.Tests/packages.config
A tweak to the build script so that it will look for xunit.console.exe in the solutions packages folder and use that to run tests if possible.
> Build script detects xunit runner

- src/IO.Ably.Tests/Realtime/ConnectionSpecs/ConnectionParameterSpecs.cs
So the tests don't need to be modified for each patch release
> Use a regex to check the PATCH portion of the version string,

- src/IO.Ably.Shared/Extensions/PresenceExtensions.cs
- src/IO.Ably.Shared/IO.Ably.Shared.projitems
- src/IO.Ably.Shared/Realtime/Presence.cs
- src/IO.Ably.Shared/Realtime/RealtimeChannel.cs
- src/IO.Ably.Shared/Types/PresenceMessage.cs
- src/IO.Ably.Tests/IO.Ably.Tests.csproj
- src/IO.Ably.Tests/Infrastructure/TaskCompletionAwaiter.cs
- src/IO.Ably.Tests/Infrastructure/TaskCountAwaiter.cs
- src/IO.Ably.Tests/Infrastructure/TestExtensions.cs
- src/IO.Ably.Tests/Realtime/ChannelSandboxSpecs.cs
- src/IO.Ably.Tests/Realtime/ConnectionSandBoxSpecs.cs
- src/IO.Ably.Tests/Realtime/PresenceSandboxSpecs.cs
- src/IO.Ably.Tests/Rest/SandboxSpec.cs
This is a continuation of the work done on PR #147 by @jeddawson in response to issue #114, the crux of which was that the library was removing Absent members instead of Present members. Fixing that lead on to implementing some of the missing Presence features.
Using the other library implementations as a guide, in particular ably-java, I have added tests to cover the parts of the spec affected by @jeddawsons original work and fixed some issues that were raised by those tests.
The new parts of the spec covered are:
- All of RTP2a/b/c/d/f/g (note RTP2e is missing at the moment)
- RTP6a/b
- RTP18a/b/c
Additionally WaitOnSync is now implemented. 
I have also fixed up the tests for:
- RTP1
- RTP4
> Added presence features covering RTP2 and others

- src/IO.Ably.Shared/EventEmitter.cs
- src/IO.Ably.Shared/Realtime/RealtimeChannel.cs
- src/IO.Ably.Shared/Transport/TransportParams.cs
- src/IO.Ably.Tests/AuthTests/AuthorisationTests.cs
- src/IO.Ably.Tests/AuthTests/RequestTokenTests.cs
- src/IO.Ably.Tests/IO.Ably.Tests.csproj
- src/IO.Ably.Tests/Realtime/ChannelSandboxSpecs.cs
- src/IO.Ably.Tests/Realtime/ChannelSpecs.cs
- src/IO.Ably.Tests/Realtime/ConnectionSandBoxSpecs.cs
- src/IO.Ably.Tests/Realtime/PresenceSandboxSpecs.cs
- src/IO.Ably.Tests/Rest/SandboxSpec.cs
- src/IO.Ably.Tests/packages.config
This PR contains updates and fixes that were done whilst working on PR #157, but that were not directly related to that work, so rather than pollute that PR I have extracted that work here. I would suggest that PR #157 is reviewed before dealing with this one.
Essentially some helpers and improvements to make some test more reliable along with a bug fix.
The headline changes are 
1. I have changed some accessors from private to internal, this allows properties to be accessed from the tests without exposing them publicly.
2. I fixed a bug where the Logger would not be set by from the ClientOptions - This would have no affect on customers as we don't allow them to set the logger in ClientOptions at the moment, but the behaviour was incorrect, as revealed by a failing test.
> Test improvements

- src/IO.Ably.Tests.NETFramework/IO.Ably.Tests.NETFramework.csproj
The project named IO.Ably.Tests.NETFramework did not have the namespace updated to match the project name, as is convention. This fixes that.
> namespace was not updated when the project name was updated

- src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionParameterSpecs.cs
This has been fixed on the v1.0 branch, but was not back ported and is causing the CI to fail for v0.8.10.
> regex would only match single digit

- src/IO.Ably.Tests.Shared/AuthTests/AuthSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/AuthTests/AuthorizeTests.cs
Fixed a white space formatting issue that had crept back in after a rebase and a tiny change to use https://echo.ably.io/respondwith?status=500 in some tests as this fails fast.
> RSA4 small tweak

- src/IO.Ably.Shared/IO.Ably.Shared.projitems
- src/IO.Ably.Shared/Realtime/Connection.cs
- src/IO.Ably.Shared/Realtime/ConnectionEvent.cs
- src/IO.Ably.Shared/Realtime/ConnectionState.cs
- src/IO.Ably.Shared/Realtime/ConnectionStateChangedEventArgs.cs
- src/IO.Ably.Tests.Shared/AuthTests/AuthSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ChannelSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionFailureSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionParameterSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/EventEmitterSpecs.cs
- src/IO.Ably.Tests.Shared/Samples/DocumentationSamples.cs
- src/IO.Ably.Tests.Shared/Samples/RealtimeSamples.cs
Changes and tests to cover 
- RTN4h
- TA1, TA2, TA3, TA5
Additionally I have fixed some RTN4x test that were not testing through the emitter and were therefore not valid.
> RTN4h, TA1, TA2, TA3, TA5

- src/IO.Ably.Shared/Realtime/Connection.cs
- src/IO.Ably.Shared/Transport/ConnectionManager.cs
- src/IO.Ably.Shared/Transport/States/Connection/ConnectionConnectedState.cs
- src/IO.Ably.Shared/Transport/States/Connection/ConnectionState.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionStateTests/ConnectedStateSpecs.cs
`(RTN24) A connected client may receive a CONNECTED ProtocolMessage from Ably at any point (though is typically triggered by a reauth, see RTC8a). The connectionDetails in the ProtocolMessage must override any stored details, see RTN21. The Connection should emit an UPDATE event with a ChannelStateChange object, which should have both previous and current attributes set to CONNECTED, and the reason attribute set to to the error member of the CONNECTED ProtocolMessage (if any). (Note that UPDATE should be the only event emitted: in particular, the library must not emit an CONNECTED event if the client was already connected, see RTN4h).	`		
`(RTN21) If the CONNECTED ProtocolMessage contains a connectionDetails property, the attributes within ConnectionDetails will be used as the defaults …
> RTN24, RTN21 and partial RTN4h

- src/IO.Ably.Shared/Transport/States/Connection/ConnectionSuspendedState.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionStateTests/SuspendedStateSpecs.cs
```(RTN7c) If a connection enters the SUSPENDED, CLOSED or FAILED state, or if the connection state is lost, and an ACK or NACK has not yet been received for a message, the client should consider the delivery of those messages as failed		```
This was a small change as RTN7c was already implemented for [CLOSED](
https://github.com/ably/ably-dotnet/blob/29c014a7d89e4627f1c288ec1f11b0001cbbeb7b/src/IO.Ably.Tests.Shared/Realtime/ConnectionStateTests/ClosedStateSpecs.cs#L90) and [FAILED](
https://github.com/ably/ably-dotnet/blob/29c014a7d89e4627f1c288ec1f11b0001cbbeb7b/src/IO.Ably.Tests.Shared/Realtime/ConnectionStateTests/FailedStateSpecs.cs#L109) but not SUSPENDED
> RTN7c Suspended

- src/IO.Ably.Shared/Realtime/RealtimeChannel.cs
- src/IO.Ably.Tests.Shared/Infrastructure/TaskCompletionAwaiter.cs
- src/IO.Ably.Tests.Shared/Realtime/ChannelSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ChannelSpecs.cs
This PR covers RTL11 and RTL11a:
- (RTL11) If a channel enters the DETACHED, SUSPENDED or FAILED state, then all messages that are still queued for send on that channel should be deleted from the queue triggering a failure for the publish or presence methods invoked for those messages
- (RTL11a) For clarity, any messages awaiting an ACK or NACK are unaffected by channel state changes i.e. a channel that becomes detached following an explicit request to detach may still receive an ACK or NACK for messages published on that channel later
> RTL11 & RTL11a

- src/IO.Ably.Shared/Realtime/ChannelMessageProcessor.cs
- src/IO.Ably.Shared/Realtime/ChannelStateChangedEventArgs.cs
- src/IO.Ably.Shared/Realtime/RealtimeChannel.cs
- src/IO.Ably.Tests.Shared/Infrastructure/TaskCompletionAwaiter.cs
- src/IO.Ably.Tests.Shared/Realtime/ChannelSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ChannelSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
This PR covers the following spec items (apologies, this is quite a large one, but it need to be done)
- (RTL2f) When a channel ATTACHED ProtocolMessage is received, the ProtocolMessage may contain a RESUMED bit flag indicating that the channel has been resumed. The corresponding ChannelStateChange (either ATTACHED per RTL2a, or UPDATE per RTL12) will contain a resumed boolean attribute with value true if the bit flag RESUMED was included. When resumed is true, this indicates that the channel attach resumed the channel state from an existing connection and there has been no loss of message continuity. In all other cases, resumed is false. A test should exist to ensure that resumed is always false when a channel first becomes ATTACHED, it is true when the channel is ATTACHED following a …
> RTL2b, RTL2f, RTL2g, RTL12 & RTL3d

- src/stylecop.json
Having checked out the project to run tests on macOS I realised that this config file was never committed as it was filtered by a gitignore rule intended for other style cop related files.
> stylecop.json

- src/IO.Ably.Shared/Realtime/Presence.cs
Small style fix. Per the style guide, properties should be placed before the constructor.
> properties should be placed before the constructor

- src/IO.Ably.Shared/Realtime/Presence.cs
- src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
- (RTP17) The Presence object is also responsible for keeping a separate copy of an object logically equivalent to the PresenceMap containing only members that match the current connectionId. Any ENTER, PRESENT, UPDATE or LEAVE event that matches the current connectionId should be applied to this object in the same way it is done for the PresenceMap. This object should be private and is used to maintain a list of members that need to be automatically re-entered by the Presence object when a Channel becomes ATTACHED with some or all continuity lost.
- -  (RTP17a) All members belonging to the current connection are published as a PresenceMessage on the Channel by the server irrespective of whether the client has permission to subscribe or the Channel is configured to publish presence …
> RTP17 and RTP17a tests

- src/IO.Ably.Tests.DotNetCore20/xunit.runner.json
- src/IO.Ably.Tests.Shared/Realtime/ChannelSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ChannelSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
CI has been unreliable most due to timeouts so I have made some tweaks to help resolve this.
In this PR I have added some longer timeouts, fixed a typo, and added some traits to existing tests that pertain to RTC1a and then streamlined said test a little.
> Test tweaks 

- src/IO.Ably.Shared/Extensions/PresenceExtensions.cs
- src/IO.Ably.Shared/Realtime/ChannelStateChangedEventArgs.cs
- src/IO.Ably.Shared/Realtime/Presence.cs
- src/IO.Ably.Shared/Realtime/PresenceMap.cs
- src/IO.Ably.Shared/Realtime/RealtimeChannel.cs
- src/IO.Ably.Tests.Shared/Infrastructure/TestHelpers.cs
- src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Rest/SandboxSpec.cs
Changes and tests for 
- (RTP19) If the PresenceMap has existing members when a SYNC is started, the client library must ensure that members no longer present on the channel are removed from the local PresenceMap once the sync is complete. In order to do this, the client library must keep track of any members that have not been added or updated in the PresenceMap during the sync process. Note that a member can be added or updated when received in a SYNC message or when received in a PRESENCE message during the sync process. Once the sync is complete, the members in the PresenceMap that have not been added or updated should be removed from the PresenceMap and a LEAVE event should be published for each. The PresenceMessage published should contain the original attributes of the presence …
> RTP19, RTP19a and RTP6b

- src/IO.Ably.Shared/AblyAuth.cs
- src/IO.Ably.Shared/AblyAuthUpdatedEventArgs.cs
- src/IO.Ably.Shared/AblyRealtime.cs
- src/IO.Ably.Shared/AblyRest.cs
- src/IO.Ably.Shared/IO.Ably.Shared.projitems
- src/IO.Ably.Shared/Realtime/ChannelMessageProcessor.cs
- src/IO.Ably.Shared/Realtime/Connection.cs
- src/IO.Ably.Shared/Realtime/RealtimeChannel.cs
- src/IO.Ably.Shared/Transport/ConnectionInfo.cs
- src/IO.Ably.Shared/Transport/ConnectionManager.cs
- src/IO.Ably.Shared/Transport/States/Connection/ConnectionClosingState.cs
- src/IO.Ably.Shared/Transport/States/Connection/ConnectionConnectedState.cs
- src/IO.Ably.Tests.Shared/AuthTests/AuthSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/AuthTests/AuthorizeTests.cs
- src/IO.Ably.Tests.Shared/IO.Ably.Tests.Shared.projitems
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionStateTests/ClosingStateSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/RealtimeSandboxSpecs.cs
Changes and tests to cover RTNb, c & d
`(RTN11) Connection#connect function:`
`(RTN11b) If the state is CLOSING, the client should make a new connection with a new transport instance and remove all references to the old one. In particular, it should make sure that, when the CLOSED ProtocolMessage arrives for the old connection, it doesn’t affect the new one.`
`(RTN11c) If the state is DISCONNECTED or SUSPENDED, aborts the retry process described in RTN14d and RTN14e and immediately tries to reconnect.`
`(RTN11d) If the state is FAILED, transitions all the channels to INITIALIZED, sets their errorReason to null, and sets the connection’s errorReason to null.`
(RTN11a is omitted as it has a [pre-existing test](https://github.com/ably/ably-dotnet/blob/5816d286d203eb6a248153b42b0e6c15668586e6/ …
> RTN11b, RTN11c, RTN11d

- src/IO.Ably.Shared/Realtime/Presence.cs
- src/IO.Ably.Tests.Shared/Infrastructure/ProtocolData.cs
- src/IO.Ably.Tests.Shared/Infrastructure/TestTransportWrapper.cs
- src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
- (RTP5a) If the channel enters the DETACHED or FAILED state then all queued presence messages will fail immediately, and the PresenceMap and internal PresenceMap (see RTP17) is cleared. The latter ensures members are not automatically re-entered if the Channel later becomes attached. Since channels in the DETACHED and FAILED states will not receive any presence updates from Ably, presence events (specifically LEAVE) should not be emitted when the PresenceMap is cleared as each presence member's state is unknown		
- (RTP5b) If a channel enters the ATTACHED state then all queued presence messages will be sent immediately and a presence SYNC may be initiated by the Ably service or the Ably service may indicate there is no SYNC necessary
> RTP5a & RTP5b

- src/IO.Ably.Shared/Extensions/PresenceExtensions.cs
- src/IO.Ably.Shared/Realtime/ChannelStateChangedEventArgs.cs
- src/IO.Ably.Shared/Realtime/Presence.cs
- src/IO.Ably.Shared/Realtime/PresenceMap.cs
- src/IO.Ably.Shared/Realtime/RealtimeChannel.cs
- src/IO.Ably.Tests.Shared/Infrastructure/ProtocolData.cs
- src/IO.Ably.Tests.Shared/Infrastructure/TestHelpers.cs
- src/IO.Ably.Tests.Shared/Infrastructure/TestTransportWrapper.cs
- src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Rest/SandboxSpec.cs
Implements RTP11 with tests
(RTP11) Presence#get function:
- (RTP11a) Returns the list of current members on the channel in a callback. By default, will wait for the SYNC to be completed, see RTP11c1
- (RTP11b) Implicitly attaches the Channel if the channel is in the INITIALIZED state. However, if the channel is in or enters the DETACHED or FAILED state before the operation succeeds, it will result in an error
- (RTP11d) If the Channel is in the SUSPENDED state then the get function will by default, or if waitForSync is set to true, result in an error with code 91005 and a message stating that the presence state is out of sync due to the channel being in a SUSPENDED state. If however the get function is called with waitForSync set to false, then it immediately returns the members …
> RTP11 and subsections

- src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
- (RTP5c2) If either a SYNC is initiated as part of the attach and the SYNC is complete, or if the resumed flag is false and a SYNC is not expected, all members not present in the PresenceMap but present in the internal PresenceMap RTP17 must be re-entered automatically by the client using the clientId and data attributes from each. The members re-entered automatically must be removed from the internal PresenceMap RTP17 ensuring that members present on the channel are constructed from presence events sent from Ably since the channel became ATTACHED
2 tests to cover the 2 initial clauses presented by the spec above:
1. If either a SYNC is initiated as part of the attach and the SYNC is complete
2. if the resumed flag is false and a SYNC is not expected
> tests for RTP5c2

- src/IO.Ably.Shared/Transport/ConnectionManager.cs
- src/IO.Ably.Shared/Transport/IConnectionContext.cs
- src/IO.Ably.Shared/Transport/States/Connection/ConnectionConnectedState.cs
- src/IO.Ably.Tests.Shared/Infrastructure/FakeConnectionContext.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
This PR covers RTN22 and RTN22a
`(RTN22) Ably can request that a connected client re-authenticates by sending the client an AUTH ProtocolMessage. The client must then immediately start a new authentication process as described in RTC8`
`(RTN22a) Ably reserves the right to forcibly disconnect a client that does not re-authenticate within an acceptable period of time, or at any time the token is deemed no longer valid. A client is forcibly disconnected following a DISCONNECTED message containing an error code in the range 40140 <= code < 40150. This will in effect force the client to re-authenticate and resume the connection immediately, see RTN15h`
As part of this work I have extracted `ConnectionInfo` and `IConnectionContext` from the `IConnectionManager.cs` file into discrete files. This …
> RTN22 and RTN22a

- src/IO.Ably.Shared/Realtime/Connection.cs
- src/IO.Ably.Shared/Transport/ConnectionManager.cs
- src/IO.Ably.Shared/Transport/States/Connection/ConnectionConnectingState.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
- (RTN15g) Connection state is only maintained server-side for a brief period, given by the connectionStateTtl in the connectionDetails, see CD2f. If a client has been disconnected for longer than the connectionStateTtl, it should not attempt to resume. Instead, it should clear the local connection state, and any connection attempts should be made as for a fresh connection
- - (RTN15g1) This check should be made before each connection attempt. It is generally not sufficient to merely clear the connection state when moving to SUSPENDED state (though that may be done too), since the device may have been sleeping / suspended, in which case it may have been many hours since it was last actually connected, even though, having been in the CONNECTED state when it was put to sleep, it has only …
> RTN15g and subsections

- src/IO.Ably.Shared/Realtime/Connection.cs
- src/IO.Ably.Shared/Transport/TransportParams.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionRecoverySpecs.cs
Updated recoveryKey to include msgSerial per v1.1 spec
- (RTN16b) Connection#recoveryKey is an attribute composed of the connectionKey, and the latest connectionSerial received on the connection, and the current msgSerial
- (RTN16f) The msgSerial component of the recoveryKey, unlike the other two components, is not sent to Ably, but rather is used to set the library internal msgSerial. (If the recover fails, the counter should be reset to 0 per RTN15c3 )
Fixed regression in RTN16e test (It was using a mock key in the old format).
> RTN16b and RTN16f

- src/IO.Ably.Shared/Realtime/ChannelStateChangedEventArgs.cs
- src/IO.Ably.Shared/Realtime/RealtimeChannel.cs
- src/IO.Ably.Tests.Shared/Realtime/ChannelSpecs.cs
ChannelStateChange
Added the source ChannelEvent to ChannelStateChange and updated existing channel spec tests to tag the various TH1-TH5 spec items that are covered
- (TH1) Whenever the channel state changes, a ChannelStateChange object is emitted on the Channel object
- (TH2) The ChannelStateChange object contains the current state in attribute current, the previous state in attribute previous
- (TH5) The ConnectionStateChange object contains the event that generated the channel state change
- (TH3) If the connection state change includes error information, then the reason attribute will contain an ErrorInfo object describing the reason for the error
- (TH4) The ChannelStateChange object contains an attribute resumed which in combination with an ATTACHED state, indicates whether the …
> ChannelStateChange (TH)

- src/IO.Ably.Shared/ClientOptions.cs
- src/IO.Ably.Tests.Shared/Rest/ChannelSpecs.cs
- src/IO.Ably.Tests.Shared/Rest/RestSpecs.cs
fix test ClientOptions_IdempotentPublishingDefaultToFalseForVersionsBelow1_1 as it assumed v1.0 was current and we are now on version 1.1
> fix test for idempotent rest publishing for version 1.1 of spec.

- src/IO.Ably.Tests.Shared/Realtime/ChannelSandboxSpecs.cs
After a recent sandbox release the test for RTL11 started failing. Increasing the timeout form 5000ms to 15000ms seem to solve the issue and doesn't compromise the test, so I am submitting that as the fix
> RTL11 test regression fix

- src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
A fix for issue #299 
These changes to test for RTN15c1 and RTN15c2 verify that the message was processed (ie publish…ed) and not just discarded.
This is demonstrated by pulling the history for the channel.
> Fix for issue #299. 

- src/IO.Ably.Shared/Realtime/Presence.cs
- src/IO.Ably.Tests.Shared/Realtime/ChannelSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
A quick PR to add a 'trait' to an existing test that covers RTP17b but was not labeled as such.
> RTP17b test identification

- src/IO.Ably.Shared/Types/ErrorInfo.cs
- src/IO.Ably.Tests.Shared/ErrorInfoTests.cs
- (TI4) Ably may additionally include a href attribute with a string value. This is included for REST responses to provide a URL for customers to find more help on the error code
- (TI5) Log entries generated from errors, where possible, should include a URL to help developers understand the error and resolve the issue. If the URL is not already present within the contents of the message attribute, then it should be included in the log entry as follows: “See [URL]”. If the href attribute is present, it should be used as the URL. If the href attribute is not present, and the code attribute is present, then the URL should be constructed as follows “https://help.ably.io/error/[CODE]”. If neither the href or code attributes are present, then an additional URL should not be included in the log …
> modifications to ErrorInfo to meet TI4 & TI5 spec

- src/IO.Ably.Shared/Realtime/Presence.cs
- src/IO.Ably.Shared/Transport/ConnectionManager.cs
- src/IO.Ably.Shared/Transport/States/Connection/ConnectionClosedState.cs
- src/IO.Ably.Shared/Transport/States/Connection/ConnectionDisconnectedState.cs
- src/IO.Ably.Shared/Transport/States/Connection/ConnectionFailedState.cs
- src/IO.Ably.Shared/Transport/States/Connection/ConnectionState.cs
- src/IO.Ably.Shared/Transport/States/Connection/ConnectionSuspendedState.cs
- src/IO.Ably.Tests.Shared/Realtime/ChannelSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
Changes to address comments in issue #298 
> If queueMessages is false, and the message is not queued, then it should be rejected at this stage, so there should be a check here for the relevant error.
The message was not being rejected, so I have added that functionality and updated the test
> RTP16b fix

- src/IO.Ably.Shared/PaginatedRequestParams.cs
- src/IO.Ably.Tests.Shared/Rest/ChannelSpecs.cs
When upgrading to 1.1 `HistoryRequestParams` was replaced with PaginatedRequestParams (as part of a process of reducing code duplication) which has created a breaking change for people moving from 0.8.
The fix presented here is to create new `HistoryRequestParams` class that inherits from `PaginatedRequestParams`.
> HistoryRequestParams fix

- src/IO.Ably.Shared/ClientOptions.cs
- src/IO.Ably.Tests.Shared/Rest/RestSpecs.cs
A fix for idempotent publishing defaulting to on in 1.1.
See Issue #275 for more
> Idempotent defaults to off for version < 1.2

- src/IO.Ably.Shared/Transport/MsWebSocketConnection.cs
This PR resolves a regression introduced with v1.1.1 that is covered by #334.
In implementing the Dispose pattern more thoroughly to solve an issue with a thread leak I had called `Dispose` on a `BlockingCollection` which is not thread safe. The `BlockingCollection`, when access after being disposed with throw a `ObjectDisposedException`, because the `BlockingCollection` is being access from a worker thread this was unhandled and could cause the application to crash.
The recommended technique with a `BlockingCollection` is to call `CompleteAdding()` to prevent more items being added to the collection and make use of a `TokenCancellationSource` passing it to `GetConsumingEnumerable()` to allow cancellation.
`Cancel`ing the `TokenCancellationSource` will cause an …
> Fix for Issue 334, incorrectly disposing of a blocking collection

- src/IO.Ably.Shared/AblyAuth.cs
- src/IO.Ably.Shared/AblyException.cs
- src/IO.Ably.Shared/ClientOptions.cs
- src/IO.Ably.Shared/Types/ErrorInfo.cs
- src/IO.Ably.Tests.DotNetCore20/IO.Ably.Tests.DotNetCore20.csproj
- src/IO.Ably.Tests.NETFramework/IO.Ably.Tests.NETFramework.csproj
- src/IO.Ably.Tests.Shared/AuthTests/AuthSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/ErrorInfoTests.cs
- src/IO.Ably.Tests.Shared/Rest/RestSpecs.cs
This is a proposal for an improvement to ErrorInfo.
I have added an InnerException property to the ErrorInfo class for situations when an ErrorInfo is created from an Exception this can be assigned, hopefully making it easier to track down issues.
I have  have also updated AuthURL error handling to make use of the InnerException property and added a test to demonstrate it, this in in response to issue #325
> Add InnerException to ErrorInfo proposal

- src/IO.Ably.Shared/Transport/MsWebSocketConnection.cs
- src/IO.Ably.Shared/Transport/MsWebSocketTransport.cs
There is potential for Logger to be null in MsWebSocketConnection after MsWebSocketTransport has been disposed as it is being nulled in the Dispose method.
I have now observed this locally using shorter < 1000ms connect/disconnect cycles.
This fix removes the assignments `Lgger = null` when disposing `MsWebSocketTransport.cs` and adds copious null guards to protect against NRE in the case the Logger does somehow become null.
> Issue 334 follow up

- src/IO.Ably.Shared/Realtime/RealtimeChannel.cs
Related to #314 
Whilst I have not been able to repeat this issue, after some investigation it was apparent that `PublishAsync` had the potential to deadlock due to a returning a `Task.Result`.
We should instead be `await`ing the `Task`, additionally as we are writing library code we can make use of `ConfigureAwait(false)` as we do not need the calling context.  
For more details of why this is so see https://msdn.microsoft.com/en-us/magazine/jj991977.aspx
> PublishAsync improvement

- src/IO.Ably.Shared/Realtime/Connection.cs
- src/IO.Ably.Shared/Realtime/RealtimeChannel.cs
- src/IO.Ably.Tests.Shared/Realtime/ChannelSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ChannelSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/RealtimeSandboxSpecs.cs
- (RTL6c1) If the connection is CONNECTED and the channel is INITIALIZED, ATTACHED, DETACHED, ATTACHING, or DETACHING then the messages are published immediately
- (RTL6c2) If the connection is INITIALIZED, CONNECTING or DISCONNECTED, and ClientOptions#queueMessages has not been explicitly set to false, then the message will be queued and delivered as soon as the connection is CONNECTED and the channel is in a state in which publishing is permitted per RTL6c1
- (RTL6c4) If the connection is SUSPENDED, CLOSING, CLOSED, or FAILED, or the channel is SUSPENDED or FAILED, the operation will result in an error
> Transient Publishing

- src/IO.Ably.Android/Platform.cs
- src/IO.Ably.NETFramework/Platform.cs
- src/IO.Ably.NETStandard20/Platform.cs
- src/IO.Ably.Shared/Realtime/Connection.cs
- src/IO.Ably.UWP/Platform.cs
- src/IO.Ably.iOS/Platform.cs
This PR is a solution to the issues raised in #331 and #332.
Regarding #332, I have added sleep/resume handling as if that were a network outage to the .NET Framework (see src/IO.Ably.NETFramework/Platform.cs below).
Instinctively I feel like this shouldn't be required for the client lib to resume from a system sleep but without it when a (Windows) system comes back from sleep the connection doesn't recover. So, perhaps this is a bit of a hack but it makes the library work as expected, so the pragmatist in me says that is OK.
It is possible that similar solutions could be added for iOS and Android, but right now I am not sure what the best options are and no one is complaining of having issues with Xamarin in that regard and testing those solutions is harder, I prefer to push that to …
> Network changed events

- src/IO.Ably.Shared/AblyAuth.cs
- src/IO.Ably.Tests.Shared/AuthTests/AuthorizeTests.cs
Proposed fix for #346 
`SetServerTimeOffset` was returning void, which is generally a bad idea except for specific use cases (async events). This is because async void methods have different error-handling semantics. 
With async void methods, as there is no Task object, any exceptions thrown will be raised directly on the SynchronizationContext (this explains why the try/catch block is not catching).
> Fix for issue #346 

- src/IO.Ably.NETFramework/Platform.cs
- src/IO.Ably.Shared/Http/AblyHttpClient.cs
- src/IO.Ably.Shared/Realtime/ChannelAwaiter.cs
- src/IO.Ably.Shared/Realtime/Presence.cs
- src/IO.Ably.Shared/Realtime/RealtimeChannel.cs
- src/IO.Ably.Shared/Transport/ConnectionManager.cs
- src/IO.Ably.Shared/Transport/MsWebSocketConnection.cs
- src/IO.Ably.Shared/Transport/MsWebSocketTransport.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
This a fix for an issue where by presence was not re-entered after a connection became disconnected (but remained in the local presence map), which is related to issue #332.
This problem was caused by some changes that were added to support the now defunct RTP3 being incorrectly implemented such that upon every connection state change a `SYNC` message was sent to the Realtime service, this had the effect of putting the Realtime service into an unexpected state (An issue has been raised internally about this by @SimonWoolf).
As RTP3 is no longer required the solution was to remove the changes relating to that (no public facing methods are affected, so this is not a breaking change) and then fix some regressions, most notably for RTP19, which seemed to just be an incorrect test. I have …
> Presence not re-entering after connect disconnect fix

- src/IO.Ably.Shared/Transport/MsWebSocketTransport.cs
- src/IO.Ably.Shared/Transport/States/Connection/ConnectionConnectedState.cs
- src/IO.Ably.Shared/Utils/TaskUtils.cs
- src/IO.Ably.Tests.Shared/IO.Ably.Tests.Shared.projitems
- src/IO.Ably.Tests.Shared/TaskUtilsTests.cs
An error was made when using `TaskUtils.RunInBackground`.
The original call was made like this
```
TaskUtils.RunInBackground(async () => await Context.RetryAuthentication(updateState: false), e => Logger.Warning(e.Message));
```
the method signature was of `RunInBackground` was
```
RunInBackground(Action action, Action<Exception> handler = null)
```
This is wrong and internally this created a Task 'wrapped' in a Task which meant the continuation (the `hander`) was applied to the incorrect (outer) Task allowing the exception on the inner Task to go unhandled.
The simplest solution I could come up with was to create and overload
```
RunInBackground(Task task, Action<Exception> handler = null)
```
and update the way this overload is invoked, thus
``` …
```
> RunInBackground bug

- src/IO.Ably.Shared/AblyAuth.cs
- src/IO.Ably.Shared/TokenDetails.cs
- src/IO.Ably.Tests.Shared/AuthTests/AuthSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Rest/RestSandBoxSpecs.cs
Even when the QueryTime time was on the library was using the default
time to verify the token returned.
Now we are using the correct time using the offset we calculated after
getting server time
Please ignore the TODO. I left it there so I can fix it in my poc branch. Otherwise there will be too many conflicts
Addresses Issue: #374
> Fix issue where incorrect time was used to check Token validity

- CHANGELOG.md
- src/CommonAssemblyInfo.cs
[Full Changelog](https://github.com/ably/ably-dotnet/compare/1.1.16...1.1.17)
**Fixed bugs:**
- Don't throw exceptions when there is a callback passed [\#397](https://github.com/ably/ably-dotnet/issues/397)
**Closed issues:**
- Remove develop branch [\#393](https://github.com/ably/ably-dotnet/issues/393)
**Merged pull requests:**
- Fix \#397. Call callback instead of throwing AblyException [\#398](https://github.com/ably/ably-dotnet/pull/398) ([marto83](https://github.com/marto83))
> Release 1.1.17

- CHANGELOG.md
- src/CommonAssemblyInfo.cs
**Fixed bugs:**
- Unexpected error: The current state \[Suspended\] does not allow messages to be sent [\#409](https://github.com/ably/ably-dotnet/issues/409)
**Merged pull requests:**
- Close issue \#409. Call error callback instead of through exception wh… [\#410](https://github.com/ably/ably-dotnet/pull/410) ([marto83](https://github.com/marto83))
> Update Changelog and assembly version

- CHANGELOG.md
- src/CommonAssemblyInfo.cs
**Closed issues:**
- Signed version of the .Net Standard 2.x assembly [\#412](https://github.com/ably/ably-dotnet/issues/412)
> Update changelog and bump assembly version to 1.1.20

- build.fsx
Fixes: #419
The problem was that for Xamarin and .net framework we have an extra step that merges newtonsoft json and it didn't copy all the required dlls.
> Update build to copy all required dlls when packaging

- CHANGELOG.md
- build.fsx
- src/CommonAssemblyInfo.cs
Fix packaging issue for .net framework, Xamarin.iOS, Xamarin.Android
- Close issue \#419. Failed to resolve IO.Ably.DeltaCodec [\#419](https://github.com/ably/ably-dotnet/issues/419) ([marto83](https://github.com/marto83))
> Bump version and add changelog

- src/IO.Ably.Shared/CustomSerialisers/MessageExtrasConverter.cs
- src/IO.Ably.Shared/Types/MessageExtras.cs
- src/IO.Ably.Tests.Shared/CustomSerializers/MessageExtrasConverterTests.cs
- src/IO.Ably.Tests.Shared/Helpers/JAssert.cs
- src/IO.Ably.Tests.Shared/Helpers/JDiff.cs
- src/IO.Ably.Tests.Shared/IO.Ably.Tests.Shared.projitems
- Refactored MessageExtras serializer
- Updated tests
- Fixes #422
> Refactor MessageExtras

- examples/AndroidSample/AblyService.cs
- examples/RealtimeChat/RealtimeChat/MainWindow.xaml.cs
- src/IO.Ably.Shared/AblyRest.cs
- src/IO.Ably.Shared/ClientOptions.cs
- src/IO.Ably.Tests.Shared/ClientOptionsTests.cs
- src/IO.Ably.Tests.Shared/IO.Ably.Tests.Shared.projitems
- src/IO.Ably.Tests.Shared/Rest/RestSpecs.cs
- src/IO.Ably.Tests/Rest/RestSpecs.cs
- src/TestHelpers/ReEnterPresenceClassic/Program.cs
- src/TestHelpers/SimulateDisconnects/Program.cs
- Added new property LogHandler to ClientOptions.
- Marked LogHander property as obsolete, delegated implementation to LogHandler.
- Refactored the change in relevant property references.
- Fixes #427.
> Fix Property Typo

- src/IO.Ably.Shared/Types/IEncodedMessage.cs
- src/IO.Ably.Shared/Types/Message.cs
- src/IO.Ably.Shared/Types/PresenceMessage.cs
Proposed fix for Issue #499. Added ConnectionKey property to Message class, PresenceMessage class, and IMessage interface. With these modifications, I have successfully published Ably messages via REST using the connectionKey of an active real-time client, which is the desired behavior.
> Add ConnectionKey property to messages

- src/IO.Ably.Shared/Realtime/IRealtimeChannel.cs
- src/IO.Ably.Shared/Realtime/RealtimeChannel.cs
- src/IO.Ably.Tests.Shared/Realtime/ChannelSpecs.cs
- src/IO.Ably.Tests.Shared/Samples/DocumentationSamples.cs
- Marked old presence history methods as deprecated.
- Introduced new history methods without ```untilAttach``` param.
- Fixes #449
> Deprecate Presence history methods

- src/IO.Ably.Shared/Transport/TransportParams.cs
Currently we receive the `heartbeat` protocol message from the
server without explicitly requesting it.  As .NET does not allow
users of the `ClientWebSocket` to observe ping-pong keep-alive
frames we are reliant on the protocol message when it comes to
knowing if the pub / sub connection is still good, end to end.
This small change *explicitly* request the protocol `heartbeat`
so we can be sure such is not redacted in the future.
This PR is part of providing support for `RTN23` in the .NET  SDK.
> Add 'heartbeat=true' to the default connection Uri

- .github/workflows/build-and-test-windows.yml
Update the `fake-cli` version to the latest: `5.20.4` as this
provides explicit support for .NET 5.
Ref: https://www.nuget.org/packages/fake-cli/5.20.4
> Update 'fake-cli' to '5.20.4'

- src/IO.Ably.Shared/MessageEncoders/MessageHandler.cs
Fix possible `NullReferenceException`, We're using a `as`
capability query rather than a cast, so `null` is of course a valid
result.
> Fix possible 'NullReferenceException'

- src/IO.Ably.NETFramework/Properties/AssemblyInfo.cs
We currently export *all* public types for COM interop.  This is not
a usage pattern we suport, i.e. using the Ably .NET assembly from
anything other than managed code.  Defaulting this to `false` also
addresses a whole bunch of build time warnings around inconsistent
COM visibility attributes.
> Stop exported by default, types for COM interop

- src/IO.Ably.Tests.DotNetCore20/IO.Ably.Tests.DotNetCore20.csproj
- src/IO.Ably.Tests.NETFramework/IO.Ably.Tests.NETFramework.csproj
We are are not currently using `Moq` or `Castle`, removing these for
now as they can always be restored later if actual usage reappears.
> Remove unused test dependencies

- src/IO.Ably.Tests.Shared/ClientOptionsTests.cs
Remove `ClientOptions` tests marked as `[Obsolete]`.
> Remove obsolete 'ClientOptions' tests

- src/IO.Ably.Shared/IoC.cs
Simple unused variable fix, presumably this was meant to be used
rather than 'reference chasing'.
> Fix unused variable

- src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionSerialSpecs.cs
This recreates an earlier PR that had hung around for a while:
https://github.com/ably/ably-dotnet/pull/505
From Sachin's original commit message:
- Remove unnecessary tests as per new spec.  
- As per RTN10, we don't need RTN10c and some part of RTN10b
> Refactor connection serial, updated

- src/IO.Ably.Shared/Capability.cs
- src/IO.Ably.Shared/DefaultLogger.cs
- src/IO.Ably.Shared/Http/AblyHttpClient.cs
- src/IO.Ably.Shared/HttpPaginatedResponse.cs
- src/IO.Ably.Shared/MessageEncoders/CipherEncoder.cs
- src/IO.Ably.Shared/MessageEncoders/JsonEncoder.cs
- src/IO.Ably.Shared/MessageEncoders/MessageEncoder.cs
- src/IO.Ably.Shared/MessageEncoders/MessageHandler.cs
- src/IO.Ably.Tests.Shared/Realtime/ChannelSpecs.cs
- src/IO.Ably.Tests.Shared/Rest/AblyHttpClientSpecs.cs
`static` methods get us one tiny step closer to pseudo pure
functions in C#.  Like `readonly` and `records` its one of those
things that in the absence of strong `const` we should leverage
as much as possible.
> Use 'static' where possible

- src/IO.Ably.Shared/Transport/MsWebSocketConnection.cs
Making the `MessageToSend` struct `readonly`.  Less is more.
> Make 'MessageToSend' struct 'readonly'

- README.md
Sachin Shinde confirms that Message Extras is supported and as such should not be listed under `Known Limitations`.
> Update 'readme.md' for message extras support

- src/IO.Ably.Tests.Shared/AuthTests/AuthSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/AuthTests/RequestTokenTests.cs
- src/IO.Ably.Tests.Shared/ClientOptionsTests.cs
- src/IO.Ably.Tests.Shared/Infrastructure/AblySpecs.cs
- src/IO.Ably.Tests.Shared/MsgPackMessageSerializerTests.cs
- src/IO.Ably.Tests.Shared/Realtime/ChannelSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ChannelsSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionStateTests/ClosingStateSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionStateTests/ConnectedStateSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionStateTests/ConnectingStateSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionStateTests/FailedStateSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionStateTests/InitializedStateSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionStateTests/SuspendedStateSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/RealtimeSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/RealtimeWorkflowSpecs.cs
- src/IO.Ably.Tests.Shared/Rest/ChannelSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Rest/RestSpecs.cs
Migrate the our `Assert.` based assertions over to `Fluent
Assertions`.  This way we get better assertion messages and
move towards having a single API for assertion testing.
> Migrate to 'Fluent Assertions'

- src/IO.Ably.Shared/AblyAuth.cs
- src/IO.Ably.Shared/AblyException.cs
- src/IO.Ably.Shared/AblyInsecureRequestException.cs
- src/IO.Ably.Shared/IO.Ably.Shared.projitems
- src/IO.Ably.Tests.Shared/AuthTests/AuthorizationTests.cs
Refactor the Ably custom exceptions giving each their own file and removing unnecessary default parameters, contructors and public state mutation.
> Refactor Ably custom exceptions

- src/IO.Ably.Shared/ClientOptions.cs
In Java it's called `fullwait` but I added a `PushAdmin` prefix so there can be no assumptions.
> Add full wait setting to be used.

- src/IO.Ably.Shared/Push/PushAdmin.cs
- src/IO.Ably.Tests.Shared/Push/PushAdminTests.cs
Adds the helper method to add device authentication to requests we make.
> Add DeviceAuthentication helper + (RSH6) tests

- src/IO.Ably.Shared/Push/IDeviceRegistrations.cs
- src/IO.Ably.Shared/Push/PushAdmin.cs
- src/IO.Ably.Tests.Shared/Push/PushAdminTests.cs
Updated the interface to return Result<DeviceRegistration> so we can return a meaningful error if the device is not found instead of null.
> (RSH1b1) get(deviceId) performs a request to /push/deviceRegistrations/:deviceId and returns a DeviceDetails object if the deviceId is found or results in a not found error if the device cannot be found. If the client has been activated as a push target device, and the specified deviceId is that of the present client, then this request must include push device authentication.
The push device authentication test will be in the next PR.
> Update DeviceRegistartion get async and add tests

- src/IO.Ably.Shared/AblyRest.cs
- src/IO.Ably.Shared/Push/PushAdmin.cs
- src/IO.Ably.Tests.Shared/Push/PushAdminTests.cs
I've started adding a way to load the persisted device and share that device among multiple rest clients but it got complicated so I deviced to leave that to a future PR. This is why there is a todo on the Device Property.
> Ensure device auth headers are included for getting a push device info

- src/IO.Ably.Shared/Defaults.cs
- src/IO.Ably.Shared/Http/AblyHttpClient.cs
- src/IO.Ably.Shared/Push/DeviceDetails.cs
- src/IO.Ably.Shared/Push/LocalDevice.cs
- src/IO.Ably.Shared/Push/PushAdmin.cs
- src/IO.Ably.Tests.Shared/Push/PushAdminSandboxTests.cs
- src/IO.Ably.Tests.Shared/Push/PushAdminTests.cs
> (RSH1b3) #save(device) issues a PUT request to /push/deviceRegistrations/:deviceId using the DeviceDetails object (and optionally a JSON-encodable object) argument. A test should exist for a successful save, a successful subsequent save with an update, and a failed save operation. If the client has been activated as a push target device, and the specified deviceId is that of the present client, then this request must include push device authentication.
I've also refactored the device security headers to constants
> Add DeviceRegistration SaveAsync logic + tests RSH1b3

- src/IO.Ably.Tests.Shared/Push/PushAdminSandboxTests.cs
- src/IO.Ably.Tests.Shared/Push/PushAdminTests.cs
These warnings are stopping the Standard and Framework builds from cleaning passing.  In the case of the Framework build one is, by default, elevated to the level of being an error.
> Clean up some new warnings.

- src/IO.Ably.Shared/Extensions/ChannelModeExtensions.cs
- src/IO.Ably.Shared/IO.Ably.Shared.projitems
- src/IO.Ably.Shared/Types/ChannelModes.cs
Move `ChannelModeExtensions` out to its own file, located along with the other 'Extensions classes.
> Move 'ChannelModeExtensions' out to its own file

- src/IO.Ably.Shared/Push/ActivationStateMachine.States.cs
The idea behind changing the signature is to simplify how the Transition function queues events that need to be executed once the Transition to a new State has happened. So the transition function will return the new state and a function to be executed straight away.
> Add CanHandleEvent and update signature for Transition

- src/IO.Ably.Shared/Push/RegistrationToken.cs
Remove unused `using`s, reorder to BCL FDG and make the type more of a value-type and immutable once created.  As and when we ever need mutability we can add it in, we're not using it right now.
> Tidy 'RegistrationToken' type

- src/IO.Ably.Shared/ClientOptions.cs
We don't need this state at the moment, as and when we re-enable `MSGPACK` we'll bring this back.
> Elide 'MSGPACK' only state

- src/IO.Ably.Shared/AblyAuth.cs
- src/IO.Ably.Shared/ApiKey.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
Replace the `40101` magic number with `ErrorCodes.InvalidCredentials` enum.
> Replace magic number with 'InvalidCredentials' enum

- src/IO.Ably.Shared/AblyAuth.cs
- src/IO.Ably.Shared/Transport/TransportParams.cs
- src/IO.Ably.Shared/Types/ErrorInfo.cs
- src/IO.Ably.Tests.Shared/Rest/RestSpecs.cs
Replace the magic number `40100` with the `ErrorCodes.Unauthorized` enum.
> Replace magic number with 'Unauthorized' enum

- src/IO.Ably.Shared/Types/ErrorInfo.cs
Replace the magic number `10000` with `ErrorCodes.NoError` enum.
> Replace magic number with 'NoError' enum

- src/IO.Ably.Shared/Realtime/RealtimeChannel.cs
- src/IO.Ably.Tests.Shared/Realtime/ChannelSpecs.cs
Replace the magic number `90007` with the `ErrorCodes.ChannelOperationFailedNoServerResponse` enum.
> Replace magic number with 'ChannelOperationFailedNoServerResponse' enum

- src/IO.Ably.Shared/Realtime/Presence.cs
Replace the magic number `90001` with the `ErrorCodes.ChannelOperationFailedWithInvalidState` enum.
> Replace magic number with 'ChannelOperationFailedWithInvalidState' enum

- src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
Replace the magic number `40130` with the `ErrorCodes.KeyError` enum.
> Replace magic number with 'KeyError' enum

- src/IO.Ably.Tests.Shared/Realtime/ChannelSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSandboxOperatingSystemEventsForNetworkSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionFailureSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionFailuresOnceConnectedSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/RealtimeSandboxSpecs.cs
Replace the magic number `40140` with the `ErrorCodes.TokenError` enum.
> Replace magic number with 'TokenError' enum

- src/IO.Ably.Shared/AblyAuth.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
Replace the magic number `40142` with the `ErrorCodes.TokenExpired` enum.
> Replace magic number with 'TokenExpired' enum

- src/IO.Ably.Tests.Shared/AuthTests/AuthSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ChannelSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/RealtimeSandboxSpecs.cs
Replace the magic number `40160` with the `ErrorCodes.OperationNotPermittedWithCapability` enum.
> Replace magic number with 'OperationNotPermittedWithCapability' enum

- src/IO.Ably.Shared/IO.Ably.Shared.projitems
- src/IO.Ably.Shared/Types/IMessage.cs
Methods in the `IMessage` interface hide those in the `IPayload` base interface.
Perhaps due to a previously interupted refactoring?
> Remove interface methods that hide those in the base

- src/IO.Ably.Tests.Shared/AuthTests/AuthSandboxSpecs.cs
If our assertions fail having the `context` as part of the failure message use useful.
> 'AuthSandboxSpecs' use unused 'context' parameter

- src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionFailuresOnceConnectedSpecs.cs
I'm not a fan of boolean parameters, they're almost entirely opaque when subsequently being read, an `enum` would be better...
> 'ConnectionSpecs' name opaque boolean parameter

- src/IO.Ably.Tests.Shared/Rest/ChannelSpecs.cs
We mean for these casts to always succeed so using 'as' just muddies the water.
Also removed an unused variable.
> Fix warning: possible null

- src/IO.Ably.Shared/Realtime/Presence.GetParams.cs
- src/IO.Ably.Shared/Realtime/Presence.QueuedPresenceMessage.cs
- src/IO.Ably.Shared/Realtime/Presence.cs
Removing the virtual decorators and sealing 'Presence' as at the present time
nothing inherits from the class so we don't need these capabilities.
> 'Presence' remove virtual as nothing inherits

- src/IO.Ably.Shared/MessageEncoders/MessageEncoder.cs
- src/IO.Ably.Tests.Shared/Realtime/ChannelSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/EventEmitterSpecs.cs
- src/IO.Ably.Tests.Shared/Rest/ChannelSpecs.cs
When calling a method that uses the 'params' keyword you don't need to explicitly create an array, the compiler takes care of this for you. It's all part of the 'params' value proposition.
> Remove redundant explicit array creation bound to 'params'

- src/IO.Ably.Shared/HttpUtility.cs
Re-express `HttpUtility` to remove the possible `NullReferenceException` warning.
> 'HttpUtility' Fix Possible 'NullReferenceException' warning

- src/IO.Ably.Shared/Push/PushRest.cs
`PushRest` doesn't need to hang on to this member state since it's just delegated down to the `Admin` property which does the holding on.
> 'PushRest' remove unused member state

- src/IO.Ably.Shared/MessageEncoders/MessageHandler.cs
- src/IO.Ably.Shared/MessageEncoders/VCDiffEncoder.cs
- src/IO.Ably.Shared/MessageEncoders/VcdiffErrorInfo.cs
- src/IO.Ably.Shared/Realtime/ChannelMessageProcessor.cs
- src/IO.Ably.Shared/Types/ErrorCodes.cs
- src/IO.Ably.Tests.Shared/Realtime/DeltaSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/DeltaSpecs.cs
Part of our slow and steady quest to zero warnings...
> Rename the 'VCDiff*' types to fix various warnings

- src/IO.Ably.Tests.Shared/AuthTests/TestAblyAuth.cs
Fixes warnings around base member parameter default values and unnecessary access.
Tidied up the type layout too to confirm to the BCL FDG.
> 'TestAblyAuth' fix various warnings

- src/IO.Ably.Shared/Types/ErrorCodes.cs
- src/IO.Ably.Shared/Types/ErrorInfo.cs
- src/IO.Ably.Tests.Shared/AuthTests/AuthSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Rest/RestInitSpecs.cs
Create the new `ErrorCodes.NoMeansProvidedToRenewAuthToken` to banish magic numbers.
> Replace magic number with new 'NoMeansProvidedToRenewAuthToken' constant

- src/IO.Ably.Tests.Shared/Rest/AblyHttpClientSpecs.cs
This group of tests just tests static functions so we don't need to hold onto an instance.  Fixed a naming and layout issue too.
> 'AblyHttpClientSpecs' fix field is assigned but never used

- src/IO.Ably.Tests.Shared/MessageEncodes/CipherEncoderTests.cs
As the field is always assigned to before being used.
> 'CipherEncoderTests' convert field to local variable

- src/IO.Ably.Shared/IO.Ably.Shared.projitems
- src/IO.Ably.Shared/Realtime/Workflows/RealtimeWorkflow.cs
- src/IO.Ably.Shared/Transport/MsWebSocketConnection.cs
- src/IO.Ably.Shared/Utils/ErrorPolicy.cs
- src/IO.Ably.Shared/Utils/TaskUtils.cs
- src/IO.Ably.Tests.Shared/IO.Ably.Tests.Shared.projitems
- src/IO.Ably.Tests.Shared/Utils/ErrorPolicyTests.cs
We need to do something more than just sending unexpected exceptions to /dev/nul so at the very least the current implementation now logs that they occured before carrying on.
> Added 'ErrorPolicy' type with 'HandleUnexpected'

- src/IO.Ably.Shared/Transport/ConnectionManager.cs
Changed the `var` declarations to ones that explicitly specify `Result` as it's not obvious from the call sight.
> 'ConnectionManager' log failure to encode message when sending

- src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionFailureSpecs.cs
We go to the trouble of creating and populating the `stateChanges` accumulator so we can at least check it's not empty at the end of a test run.
> 'ConnectionFailureSpecs' check 'stateChanges' accumulator

- src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionFallbackSpecs.cs
We're taking the trouble to create and populate this, so at the very least (for now) we should check there's actually something in it at the end of the test.
> 'ConnectionFallbackSpecs' check 'states' accumulator

- src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
Unfortunately checking for `null` using `FluentAssertions` does not count as checking when it comes to static code analysis. This change addresses this, refactoring the code around getting a channel to reduce duplication in doing so.
Also tidied up the class(es) layout to bring them into line more with the BCL FDG.
> 'PresenceSandboxSpecs' fix possible 'NullReferenceException' warnings

- src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
We don't need to use `LINQ` here, the collection maintains a `Count` property.
> 'PresenceSandboxSpecs' use property 'Count' rather than an extension method

- src/IO.Ably.Shared/TokenRequest.cs
The `Now` property is only used by the implementation.  It doesn't need to be a property at all.  Making it a field, and `readonly` while we're there.
> 'TokenRequest' replace property with field

- src/IO.Ably.Shared/Realtime/Workflows/RealtimeCommands.cs
- src/IO.Ably.Shared/Realtime/Workflows/RealtimeWorkflow.cs
- src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
Rename the `SetInitStateCommand` to be `ForceStateInitializationCommand` and remove the unused property.
> 'SetInitStateCommand' refactor to remove unused property

- src/IO.Ably.Tests.Shared/Rest/ChannelSpecs.cs
Fixes:
- Put constructor initializers on their own line
- Code should not contain multiple blank lines in a row
> 'ChannelSpecs' Fix warnings

- src/IO.Ably.Tests.Shared/Push/PushChannelTests.cs
Fixes warning about code not containing multiple blank lines in a row.
> 'PushChannelTests' Fix code layout

- src/IO.Ably.Tests.Shared/Rest/SandboxSpecs.cs
We get a lot of tests failing because of time outs.  This PR is an investigation into whether we need to extend our default time-outs when executing tests under GitHub Actions where test execution times seem to vary widely.
> 'SandboxSpecs' increase 'WaitFor' period

- src/IO.Ably.Shared/Realtime/RealtimeChannel.cs
> 'RealtimeChannel' replace lambda with local function

- src/IO.Ably.Shared/Realtime/RealtimeChannels.cs
> 'RealtimeChannels' replace lambda with local function

- src/IO.Ably.Shared/Realtime/ChannelAwaiter.cs
> 'ChannelAwaiter' replace lambda with local function

- src/IO.Ably.Tests.Shared/AuthTests/AuthSandboxSpecs.cs
> 'AuthSandboxSpecs' replace lambda with local function

- src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionFailuresOnceConnectedSpecs.cs
> 'ConnectionFailuresOnceConnectedSpecs' replace lambda with local function

- src/IO.Ably.Tests.Shared/Samples/DocumentationSamples.cs
Various clean-ups since this is meant to be a teaching aid:
1. Replace lambdas with local functions.
2. Consistent style of single line comments.
3. Consistent use of string-interpolation.
4. Stop using now `[Obsolete]` APIs.
5. Make type and members `static` to better convery that each method is isolated.
> 'DocumentationSamples' refactor for consistency

- src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionFailureSpecs.cs
> 'ConnectionFailureSpecs' replace lambda with local function

- src/IO.Ably.Shared/AblyAuth.cs
Now I store the previous value, set it and check it after it has been set. This is to avoid issues in priority where if ConnectionClientId is set then CurrentToken.ClientId doesn't trigger a change. 
@sacOO7 I've also created issue https://github.com/ably/ably-dotnet/issues/930 and updated the TODO to make it clear what needs to happen. Thanks for the comments on the previous branch.
> Fix how the ClientIdNotification works

- src/IO.Ably.Shared/HttpPaginatedResponse.cs
The `First` and `FirstAsync` members do not hide an accessible member in the base. The `new` keyword is not required.
> Fix member does not hide an accessible member

- src/IO.Ably.Shared/Push/ListDeviceDetailsRequest.cs
Using the `new` keyword to make this explicit, Martin to confirm please.
> 'ListDeviceDetailsRequest' member hides inherited member

- src/IO.Ably.Shared/Push/ListSubscriptionsRequest.cs
`ListSubscriptionsRequest.Empty(int?` hides inherited member `PaginatedRequestParams.Empty`. Using `new` to make this explicit, Martin to check please.
> 'ListSubscriptionRequest' member hides inherited member

- src/IO.Ably.Tests.Shared/Realtime/ChannelSpecs.cs
The `WhenDetachedOrFailed_AllQueuedPresenceMessagesShouldBeDeletedAndFailCallbackInvoked` test needs more analysis.
> 'PresenceSpecs' skip intermittently failing test

- src/IO.Ably.Tests.Shared/Realtime/ConnectionSandboxOperatingSystemEventsForNetworkSpecs.cs
In the skipped test `WhenOperatingSystemNetworkBecomesAvailableAndStateIsDisconnected_ShouldTransitionTryToConnectImmediately` we where creating and populating a collection to no end.  This quick fix addresses that.  This test needs further work.
> Fix collections content is never queried warning

- src/IO.Ably.Tests.Shared/Samples/DocumentationSamples.cs
- src/IO.Ably.Tests.Shared/Samples/RealtimeSamples.cs
The sample code takes the form of small snippets that focus on use-cases and common workflows. These samples are by necessity brief and often omit error checking etc so as not to distract, as such the samples generate a lot of warnings about unused variables etc.
> Disable code analysis for sample code

- src/IO.Ably.Shared/Realtime/Workflows/RealtimeWorkflow.cs
Observed during test runs, it is possible to get a command with a non-null `Exception` but a null `ErrorInfo`.
> 'RealtimeWorkflow' fix 'NullReferenceException'

- src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
- src/IO.Ably.Tests.Shared/Rest/RestSpecs.cs
Fundamentally we should use an 'old fashioned' cast here, not the `as` operator since we're not saying 'Do you have this capability?' (which might return `null`) but 'I am *expecting* you to be this thing!'
> Fix possible 'NullReferenceException' warnings

- src/IO.Ably.Tests.Shared/Realtime/MockHttpRealtimeSpecs.cs
There where no `overrides` for this and besides its use was generating a 'virtual method call in constructor' warning. Two birds, one stone.
> Remove speculative generalization

- src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
The parameter `timeoutMs` has the same default value.
> Remove redundant argument with default value

- src/IO.Ably.Shared/Transport/States/Connection/ConnectionStateBase.cs
Since we have no overrides of `IsUpdate` the easiest fix is to remove it's `virtual`-ness.
> Fix virtual method call in constructor warning

- src/IO.Ably.Shared/Capability.cs
We're reading rather than writing so in this specific case it's OK.
> Make explicit the intended co-variant array converion

- src/IO.Ably.Tests.Shared/DefaultTests.cs
- src/IO.Ably.Tests.Shared/Rest/ChannelSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Rest/RestSpecs.cs
The parameter `protocol` has the same default value.
> Fix redundant argument with default value

- src/IO.Ably.Tests.Shared/Realtime/ConnectionSandBoxSpecs.cs
Unfortunately code-analysis doesn't take into account checks made with the Fluent Assertions library.
> Fix possible 'NullReferenceException' warning

- src/IO.Ably.Tests.DotNetCore20/IO.Ably.Tests.DotNetCore20.csproj
- src/IO.Ably.Tests.NETFramework/IO.Ably.Tests.NETFramework.csproj
- src/IO.Ably.Tests.Shared/AuthTests/AuthorizationTests.cs
- src/IO.Ably.Tests.Shared/AuthTests/RequestTokenSpecs.cs
- src/IO.Ably.Tests.Shared/AuthTests/ServerTimeTests.cs
- src/IO.Ably.Tests.Shared/LoggerTests.cs
- src/IO.Ably.Tests.Shared/Push/PushAdminTests.cs
- src/IO.Ably.Tests.Shared/Push/PushChannelTests.cs
- src/IO.Ably.Tests.Shared/Realtime/ChannelSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ChannelSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ChannelsSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionFailureSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionFailuresOnceConnectedSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/ConnectionSpecs/ConnectionParameterSpecs.cs
- src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Rest/ChannelSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Rest/ChannelSpecs.cs
- src/IO.Ably.Tests.Shared/Rest/RestSandBoxSpecs.cs
- src/IO.Ably.Tests.Shared/Rest/RestSpecs.cs
Update our `FluentAssertions` dependency from `5.10.3` to the latest `6.2.0`.
As the `FluentAssertions` API has changed in places some interventions on our side were needed on our side.
Note that in the `5.10.3` API the precision when comparing dates and times was represented as an `int` with a default value of 20 (milliseconds).
> Update our 'FluentAssertions' dependency

- src/IO.Ably.Shared/Push/PushRealtime.cs
Fixes
[CA1063](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1063)
when building for .NET 6.0.100 .
This relates to the GitHub Issues:
[1007](https://github.com/ably/ably-dotnet/issues/1007),
[523](https://github.com/ably/ably-dotnet/issues/523)
> 'PushRealtime' Fix .NET 6 build error

- src/IO.Ably.Shared/Push/ActivationStateMachine.cs
Fixes
[CA1001](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1001) when building for .NET 6.0.100 .
> 'AcivationStateMachine' fix .NET 6 build error

- src/IO.Ably.Shared/Realtime/Handlers.cs
Fixes [CA1001](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1001) when building for .NET 6.0.100 .
> 'Handlers' fix .NET 6 build error

- src/IO.Ably.Shared/Realtime/Workflows/RealtimeWorkflow.cs
Fixes [CA1001](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1001) when building for .NET 6.0.100 .
> 'RealtimeWorkflow' fix .NET 6 build error

- src/IO.Ably.Shared/Push/PushAdmin.cs
Fixes [CA1033](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1033) when building for .NET 6.0.100 .
> 'PushAdmin' fix .NET 6 build error

- src/IO.Ably.Shared/Realtime/RealtimeChannels.cs
Fixes [CA1033](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1033) when building for .NET 6.0.100 .
> 'RealtimeChannels' fix .NET 6 build error

- src/IO.Ably.Shared/AblyRealtime.cs
We can't just apply`sealed` to `AblyRealtime` since this would be a breaking change, rather we have to add `virtual` just in case anyone has derived from the type [CA1001](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1001).
> 'AblyRealtime' fix .NET build error

- src/IO.Ably.Shared/EventEmitter.cs
Fixes [CA1001](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1001) when building for .NET 6.0.100 . Basically we have a type as a member that requires explicit disposing, so we should implement IDisposable ourselves and call the member `dispose` as appropriate.
> 'EventEmitter' fix .NET 6 build error

- src/IO.Ably.Shared/Realtime/Presence.cs
Fixes [CA1001](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1001) when building for .NET 6.0.100 . Basically we have a type as a member that requires explicit disposing, so we should
implement `IDisposable` ourselves and call the member `dispose` as appropriate.
> 'Presence' fix .NET 6 build error

- src/IO.Ably.Shared/Rest/RestChannel.cs
Fixes [CA1033](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1033) when building for .NET 6.0.100 .
> 'RestChannel' fix .NET 6 build error

- src/IO.Ably.Shared/Rest/RestChannels.cs
Fixes [CA1033](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1033) when building for .NET 6.0.100 .
> 'RestChannels' fix .NET 6 build error

- src/IO.Ably.Shared/Transport/MsWebSocketConnection.cs
Disables [CA1063](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1063) when building for .NET 6.0.100 . Need to recover the evidence trail that led to this code...
> 'MsWebSocketConnection' Disable .NET 6 build error

- src/IO.Ably.Shared/Transport/MsWebSocketTransport.cs
Disables [CA1063](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1063) when building for .NET 6.0.100 . Need to recover the evidence trail that led to this code...
> 'MsWebSocketTransport' disable .NET 6 build error

- src/IO.Ably.Shared/Encryption/Crypto.cs
We need to update our usage of the [obselete](https://docs.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0023)  `RNGCryptoServiceProvider`.  For now I will just `pragma around` this but it will need to be properly addressed before we're production ready on .NET 6.
This relates to the GitHub Issues: [1007](https://github.com/ably/ably-dotnet/issues/1007), [523](https://github.com/ably/ably-dotnet/issues/523), [1054](https://github.com/ably/ably-dotnet/issues/1054)
> 'Crypto' suppress (for now) .NET 6 build error

- src/IO.Ably.Tests.Shared/AuthTests/AuthSandboxSpecs.cs
As part of the .NET 6 support, applying the advice [here](https://docs.microsoft.com/en-us/dotnet/api/system.uri.escapeuristring?view=net-6.0) :
"`Uri.EscapeUriString` can corrupt the Uri string in some cases. Consider using `Uri.EscapeDataString` for query string components."
> Replace 'Uri.EscapeUriString' with 'Uri.EscapeDataString'

- src/IO.Ably.Tests.Shared/LoggerTests.cs
- src/IO.Ably.Tests.Shared/Push/ActivationStateMachineTests.cs
- src/IO.Ably.Tests.Shared/Push/LocalDeviceTests.cs
Applying `sealed` to these test classes as part of [CA1063](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1063) guidance.
> Fix 'CA1063' issues

- src/IO.Ably.Tests.Shared/Infrastructure/AblyRealtimeSpecs.cs
- src/IO.Ably.Tests.Shared/Infrastructure/ConditionalAwaiter.cs
- src/IO.Ably.Tests.Shared/Infrastructure/TaskCountAwaiter.cs
- src/IO.Ably.Tests.Shared/Infrastructure/TimeoutCallback.cs
- src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Rest/RestSpecs.cs
- src/IO.Ably.Tests.Shared/Rest/SandboxSpecs.cs
Class that have member(s) (field(s)) that implement IDisposable should themselves implement IDisposable and delegate to the appropriate member(s) (field(s)) as appropriate.
> Tests need to implement IDisposble

- src/IO.Ably.Shared/Types/LockedList.cs
We're explicitly using the double-check locking pattern so in this specific case its OK to suppress the warning about inconsistent synchronization on the `_items` field.
> 'LockedList' Suppress inconsistent sync on field warning

- src/IO.Ably.Shared/Realtime/Presence.cs
We don't need to call `GC.SuppressFinalize` on a type without a destructor.
> 'Presence' Fix warning about call to 'SuppressFinalize' being used

- README.md
Checked with Martin and we don't need the:
'Xamarin and VS 2017'
'Significant changes in 1.1.15'
sections any more.
> Remove defunct 'README.md' sections

- src/IO.Ably.Tests.Shared/Infrastructure/ResourceHelper.cs
Addresses:
Return value of `[MustUseReturnValue]` annotated method is not used
Return value of method is not used. Fewer bytes can be read than requested
> Fix '[MustUseReturnValue]' warning

- src/IO.Ably.NETFramework/IO.Ably.NETFramework.csproj
- src/IO.Ably.NETFramework/app.config
- src/IO.Ably.Tests.NETFramework/App.config
- src/IO.Ably.Tests.NETFramework/IO.Ably.Tests.NETFramework.csproj
@sacOO7 ran into a CI build issue involving `4.6.1`. After some investigation it turns out we need to move on to `4.6.2` because:
```
The following versions of .NET Framework will reach end-of-support on April 26, 2022: 4.5.2, 4.6, and 4.6.1. After this date, security fixes, updates, and technical support for these versions will no longer be provided.
If you're using .NET Framework 4.5.2, 4.6, or 4.6.1, update your deployed runtime to a more recent version, such as .NET Framework 4.6.2, before April 26, 2022 in order to continue to receive updates and technical support.
```
[ref](https://docs.microsoft.com/en-gb/dotnet/framework/install/guide-for-developers)
[GitHub Issue](https://github.com/ably/ably-dotnet/issues/1126)
> Increase .NET Framework min ver from 4.6.1 to 4.6.2

- README.md
We can't be sprinkling links to the GitHub ids of individual team members in documentation (though, change log is a clear exception to that).
Replaces the references added in https://github.com/ably/ably-dotnet/pull/1131 (which I wasn't around to review before it merged) with role titles.
> Refine release PR approvals guidance

- src/IO.Ably.NETStandard20/Properties/AssemblyInfo.cs
- Fixes #1123 
- Doesn't affect the published NuGet package, since `PACKAGE` flag is set while packaging.
> Update netstandard assemblyInfo

- PushNotifications.md
- README.md
- examples/DotnetPush/DotnetPush.Android/MainActivity.cs
- examples/DotnetPush/DotnetPush.iOS/AppDelegate.cs
- src/IO.Ably.Shared/AblyRest.cs
- src/IO.Ably.Shared/Push/DeviceDetails.cs
- src/IO.Ably.Shared/Push/IDeviceRegistrations.cs
- src/IO.Ably.Shared/Push/IPushChannelSubscriptions.cs
- src/IO.Ably.Shared/Push/PushAdmin.cs
- src/IO.Ably.Shared/Rest/ChannelOptions.cs
- src/IO.Ably.Shared/Types/ProtocolMessage.cs
- src/IO.Ably.Tests.Shared/ChannelOptionsExtensions.cs
Updatre any documentation URLs in the Markdown Files from `ably.com/documentation` to `ably.com/docs`.
> Update documentation URLs

- src/IO.Ably.Shared/Types/Message.cs
- src/IO.Ably.Shared/Types/MessageExtras.cs
- src/IO.Ably.Tests.Shared/Realtime/ProtocolMessageTests.cs
Sachin caught the issue when serialising a `ProtocolMessage` containing Messages with only `MessageExtras` and no other properties. As Message extras was not in the Equality comparison the `OnSerializing` method in `ProtocolMessage` thought all the messages were empty and set the whole `Messages` property to `null` thus causing issues.
I don't think it would have caused any real user issues because having a message with only Extras is a pointless. It did however cause issues when Sachin enabled Debug logging in the RealtimeWorkflow class.
> Add message extras to the Message equality comparison

- README.md
Remove support for Windows 7 but leave the whole question of .NET Framework vs .NET Core and .NET Standard 2.0 alone.
> Remove support for 'Windows 7'.

- README.md
Given that Visual Studio 2019 is effectively end of life at this point we should remove mention of Visual Studio 2017 from the documentation.
A follow-up PR will replace mention of Visual Studio 2022.
> Remove mention of Visual Studio 2017

- .github/dependabot.yml
I need to do this in order to prevent Dependabot from creating a `dependencies` label in this repository every time it creates a PR.
The `directory` and `schedule.interval` options are required and it doesn't look like it's possible to tell them to inherit the defaults. This is why I have had to explicitly give them values here. In turn I've upgraded from 'daily' to 'weekly' for interval as that feels more appropriately prompt.
see: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-the-dependabotyml-file
Akin / related: https://github.com/ably/ably-js/pull/1080
> Override the default Dependabot configuration for NuGet

- src/IO.Ably.Shared/Realtime/Workflows/RealtimeWorkflow.cs
- src/IO.Ably.Shared/Transport/ConnectionManager.cs
- src/IO.Ably.Shared/Types/ErrorInfo.cs
- src/IO.Ably.Tests.Shared/Infrastructure/TestTransportFactory.cs
- src/IO.Ably.Tests.Shared/Infrastructure/TestTransportWrapper.cs
- src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
~Fixed queueing that happens for following states~
~CONNECTIONCLOSING, CONNECTIONCLOSED, CONNECTIONSUSPENDED, CONNECTIONFAILED~
~when `QueueMessages=false`~
- Fixed queueing where RealtimeWorkflowScheduler is queuing messages on connected state and sending them after client is disconnected.
- Added missing check to fix the same.
- Implemented https://github.com/ably/specification/issues/134
- Fixed #1219
> Fix QueueMessages when set to false

- README.md
- src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
- Previous versions reached end of support https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/
- Link to internal discussion - https://ably-real-time.slack.com/archives/C0174D4AP4P/p1685035878236699
> Fix README supported platforms + flaky tests

- README.md
- src/IO.Ably.Shared/Rest/IRestChannel.cs
- src/IO.Ably.Shared/Rest/RestChannel.cs
- src/IO.Ably.Tests.Shared/Rest/ChannelSandboxSpecs.cs
- extending PR https://github.com/ably/ably-dotnet/pull/1264
- Fixed #1240
> Add async version of channel status

- README.md
- src/IO.Ably.Shared/Extensions/PresenceExtensions.cs
- src/IO.Ably.Shared/Realtime/ChannelMessageProcessor.cs
- src/IO.Ably.Shared/Realtime/Presence.cs
- src/IO.Ably.Shared/Realtime/RealtimeChannels.cs
- src/IO.Ably.Shared/Realtime/RecoveryKeyContext.cs
- src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs
- src/IO.Ably.Tests.Shared/Rest/SandboxSpecExtension.cs
- Fixed #1271 
- Fixes part of presence and no-connection-serial ( as discussed during review of ably-go and ably-cocoa )
> Fix spec RTL12
